Support keyword arguments in plt.gcf as in plt.gca
matplotlib/matplotlib pull request #18379
Opened 2020-08-30 17:51 UTC by alexiscoutinho

## PR Summary
This PR standardizes the `plt.gc_` interface. Since `plt.gca` allows for custom `Axes` creation if none exists, so should `plt.gcf` support custom `Figure` creation.

## PR Checklist

- [N/A] Has pytest style unit tests (and `pytest` passes).
- [Y] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [Y] New features are documented, with examples if plot related.
- [Probably] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [Y] Conforms to Matplotlib style conventions (install `flake8-docstrings` and `pydocstyle<4` and run `flake8 --docstring-convention=all`).
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

2020-08-30 18:39 UTC, anntzer requested changes
I think it was a mistake to let gca() take kwargs (see discussion at https://github.com/matplotlib/matplotlib/issues/10700); let's not do the same mistake for gcf().

2020-08-31 19:36 UTC, alexiscoutinho commented
Then why wasn't that discussion closed and the issue patched?

2020-08-31 19:50 UTC, jklymak commented
It never came to a definitive conclusion.  Can you explain why you want gcf to do this instead of just using plt.figure?

2020-09-02 12:46 UTC, alexiscoutinho commented
Suppose you are working on a module in another package and dealing specifically with large figures for multiple panels (debug plots, for example). A good function/method interface should handle explicit and implicit Figure forwarding as well as create one if none exists. However, the latter two rely on `gcf` and there is no way for the external module to know (unless it used the very internal `figManager`) if the Figure it will work with was adequately created elsewhere by the user in the user code or automatically/inappropriately by `gcf`. Without this knowledge, the module can't dynamically recreate the Figure with an appropriate size through `plt.figure`. Therefore, it would be very useful if the module could be guaranteed an appropriate Figure through `gcf` with `kwargs`, kind of how dictionaries work. Another way to solve this problem, albeit cumbersome, would be to force the module to actually test the parameters of the returned Figure from `gcf`. Or even, create some sort of flag indicating if the Figure is from the user or from the default `plt.figure` (broken/bad in some circumstances). I think you will agree that the first of the three solutions is better.

2020-09-02 13:08 UTC, anntzer commented
A current figure exists if `plt.get_fignums() != []` (for example).

2020-09-02 14:33 UTC, alexiscoutinho commented
If you prefer others using that check instead of `kwargs`, then I understand. Will close the PR if the discussion is settled.

2020-09-02 16:07 UTC, jklymak commented
The issue w this pr in my mind is that by passing kwargs it implies that it will return a current figure with those kwargs.  This PR doesn't do that, and I dont think we should do that.  

I dont think an external module should implicitly use the current figure.  It could explicitly take a figure as a kwarg and make a new figure if that kwarg is not specified.  But I guess that is a taste issue.

2020-09-03 15:19 UTC, alexiscoutinho commented
Seeing that there are alternatives to get the desired behavior in both simple (like in my case) and complex situations, I somewhat agree with and accept the current `gcf` implementation.

2020-09-03 15:19 UTC, closed without merging

2020-09-05 20:14 UTC, tacaswell commented
Thanks for being understanding @alexiscoutinho .  Hopefully we will hear from you again!