Deprecate imread() reading from URLs
matplotlib/matplotlib pull request #18649
Opened 2020-10-03 20:45 UTC by timhoffm

## PR Summary

Closes #18648.

2020-10-05 20:27 UTC, dopplershift approved these changes

2020-10-05 20:32 UTC, jklymak approved these changes

2020-10-05 20:33 UTC, jklymak commented
recyclying to get doc build to rerun...

2020-10-06 00:08 UTC, QuLogic commented on doc/api/next_api_changes/deprecations/18649-TH.rst
> +reading using ``urllib.request.urlopen()``.
As part of the standard library, shouldn't this be link-able?

2020-10-06 16:19 UTC, tacaswell commented
The user also has to do a bit more jiggery-pokery than just `urlopen` as pillow expects to be able to seek on the buffer and what comes back from urlopen does not support seek (see discussion in https://github.com/matplotlib/matplotlib/issues/18129). 

The documented incantation needs to be `image.imread(io.BytesIO(urllib.request.urlopen(url).read()))` or `image.imread(io.BytesIO(requests.get(url).content))`.

I suspect we should also abandon most of the png guessing code and just let pillow infer as much as it wants to.  I think this would make our code simpler (as it is almost a completed drop-through to pillow) and make it more functional (it will open things other than png from a url).

 I am :+1: on deprecating this, but we need to provide more guidance about what to replace it with.

2020-10-06 16:23 UTC, tacaswell requested changes
Needs better docs on path away from imread.

Should probably also have, "Use `PIL.image.open(urlopen(url))`" as an option too.

2020-10-06 21:35 UTC, timhoffm commented
:+1: on the suggestions.

Anybody, feel free to amend. I'm not in word-picking mood right now.

2021-01-27 21:12 UTC, jklymak commented
close in favour of #19367

2021-01-27 21:12 UTC, closed without merging