Remove unused/deprecated AVConv_ classes
matplotlib/matplotlib pull request #18666
Opened 2020-10-05 22:24 UTC by Tranquilled

## PR Summary

Removes AVConvBase et al. and a related method in FFMpegBase that refers to a deprecated Ubuntu release. The deprecation warnings (which raise errors during tests) say that these classes will be removed by version 3.5, and they don't seem to be used by any other code in this version.

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and `pydocstyle<4` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

2020-10-05 23:02 UTC, QuLogic commented
3.4 is not out yet, so unfortunately, this cannot be done until then.

2020-10-05 23:04 UTC, QuLogic requested changes
Things deprecated in 3.3 cannot be removed until 3.5.

2020-10-05 23:08 UTC, Tranquilled commented
> Things deprecated in 3.3 cannot be removed until 3.5.

That's fair. Can I just leave the branch here until then? I notice that the circleCI tests are failing, anyway.

2020-10-05 23:58 UTC, QuLogic commented
Sure, but you would need to fix the doc build before it is eventually merged.

2020-10-06 00:31 UTC, QuLogic commented
Also, removals should get an [API note](https://matplotlib.org/devdocs/api/next_api_changes/removals/00001-ABC.html).

2020-10-06 00:42 UTC, jklymak commented
I'm not clear how we resurface this whenever 3.5 comes out....

2020-10-06 00:56 UTC, dopplershift commented
By milestoning for 3.5?

2020-10-06 00:58 UTC, jklymak commented
Fair - I wasn't sure what our milestone guidelines were.

2021-04-06 22:31 UTC, QuLogic commented
This can go in now, but it needs an API note.

2021-07-06 08:07 UTC, QuLogic commented
Thanks for the PR, but this was complete in #20465.

2021-07-06 08:07 UTC, closed without merging