Also fix tk key mapping, following the same strategy as for gtk.
matplotlib/matplotlib pull request #18693
Opened 2020-10-08 20:58 UTC by anntzer

Some keys are still misreported, e.g. numpad keyreleases (keypresses are
fine), but I think this is already an improvement.

(followup to https://github.com/matplotlib/matplotlib/pull/17791)

## PR Summary

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and `pydocstyle<4` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

2020-10-09 03:14 UTC, QuLogic requested changes
While this fixes the number pad, it breaks the arrow keys.

2020-10-09 03:14 UTC, QuLogic commented on doc/api/next_api_changes/behavior/17791-AL.rst
> +The handling of non-ascii keypresses (as reported in the KeyEvent passed to
Revert this change.
```suggestion
The handling of non-ASCII keypresses (as reported in the KeyEvent passed to
```

2020-10-09 07:45 UTC, anntzer commented on doc/api/next_api_changes/behavior/17791-AL.rst
> +The handling of non-ascii keypresses (as reported in the KeyEvent passed to
yup (rebase gone wrong)

2020-10-09 07:45 UTC, anntzer commented
good catch, now fixed.  Also found that I needed to fix pageup/pagedown, done.

2020-10-10 05:41 UTC, QuLogic approved these changes
Seems to work, but given the removed comments in the code, it might be nice to get someone on macOS to test.

2020-10-10 05:41 UTC, QuLogic commented on doc/api/next_api_changes/behavior/17791-AL.rst
> +Unicode characters (e.g., €), and respects better NumLock on the numpad.
```suggestion
Unicode characters (e.g., €), and better respects NumLock on the numpad.
```

2020-10-10 05:41 UTC, QuLogic commented on lib/matplotlib/cbook/__init__.py
> +    The unicode key is checked first; this avoids having to list most printable
```suggestion
    Convert a Unicode key or X keysym to a Matplotlib key name.

    The Unicode key is checked first; this avoids having to list most printable
```

2020-10-10 10:35 UTC, anntzer commented
both comments handled, agreed physically testing on a mac would be nice.

2020-10-10 13:27 UTC, timhoffm approved these changes

2020-10-10 13:27 UTC, merged