Remove "Demo" from example titles (part 2)
matplotlib/matplotlib pull request #18867
Opened 2020-11-01 21:08 UTC by timhoffm

## PR Summary

More cleanup like #18858.

2020-11-01 21:09 UTC, timhoffm commented on examples/event_handling/figure_axes_enter_leave.py
> -fig2, (ax, ax2) = plt.subplots(2, 1)
fig2 is just an exact copy of the fig1 example.

2020-11-02 17:08 UTC, story645 requested changes
It looks like a stray notebook (untitled6) got included?

2020-11-02 23:55 UTC, QuLogic commented on examples/event_handling/coords_demo.py
> +==========================
```suggestion
===========================
Mouse move and click events
===========================
```

2020-11-02 23:55 UTC, QuLogic commented on examples/event_handling/figure_axes_enter_leave.py
> +=================================
```suggestion
==================================
Figure/Axes enter and leave events
==================================
```

2020-11-02 23:55 UTC, QuLogic commented on examples/subplots_axes_and_figures/multiple_figs_demo.py
> +    to use the object-oriented approach and call methods on figure and Axes
This is definitely talking about the class.
```suggestion
    to use the object-oriented approach and call methods on Figure and Axes
```

2020-11-03 01:50 UTC, story645 approved these changes

2020-11-03 23:37 UTC, merged