Remove Artist.eventson and Container.eventson
matplotlib/matplotlib pull request #18910
Opened 2020-11-06 22:49 UTC by timhoffm

## PR Summary

They are unused.

Closes #4877.

2020-11-07 08:21 UTC, QuLogic commented
No deprecation?

2020-11-07 12:34 UTC, timhoffm commented
This has only ever existed as an attribute set in `__init__`. Does not appear in the documentation. Did not have any functionality for years (possibly ever).

Given that, it's extremely unlikely anybody is using it, and I dare removing without deprecation fuss.

2020-11-10 00:55 UTC, QuLogic approved these changes

2020-11-10 20:05 UTC, anntzer requested changes
messed up rebase.  anyone can dismiss once fixed.

2020-11-17 20:28 UTC, merged