DOC: fix typos
matplotlib/matplotlib pull request #18980
Opened 2020-11-19 18:41 UTC by luzpaz

Found using `codespell v2.0.dev`  
```
codespell -q 3 -S ./extern,./doc/users/credits.rst,./doc/api/prev_api_changes,./doc/users/prev_whats_new -L afe,ans,axises,ba,coo,flate,fo,hist,inout,ment,nd,offsetp,oly,ot,te,thisy,vas,whis,wit
```

2020-11-19 20:21 UTC, dopplershift approved these changes
Thanks for the contribution!

2020-11-19 20:32 UTC, jklymak commented
We periodically get PRs like this, which is great, but they are disruptive in that they hit a bunch of files trivially.  Have we given any thought to just running codespell as part of CI, just like we run flake8?

2020-11-19 21:39 UTC, QuLogic reviewed
Can you also fix this new typo?
https://github.com/matplotlib/matplotlib/pull/18976/files#diff-33fca2ac0f7a278ffa15904a36c488500a9a4f594094e4bbffb1a10d7e9948afR30

2020-11-19 21:39 UTC, QuLogic commented on examples/axisartist/demo_curvelinear_grid2.py
> +Demo Curvilinear Grid2
This one is on purpose; see the filename and classes used. Maybe it should be `CurveLinear` in the title instead, though?

2020-11-19 21:39 UTC, QuLogic commented on tutorials/toolkits/axisartist.py
> +   Demo Curvilinear Grid
Ditto

2020-11-19 21:39 UTC, QuLogic commented on tutorials/toolkits/axisartist.py
> +   Demo Curvilinear Grid
Ditto.

2020-11-19 21:42 UTC, QuLogic commented
The trouble with running it in CI is that there are a lot of false positives; I'm sure @luzpaz had to spend a while cherry picking the bits that are actually errors.

Possibly we could use reviewdog to limit the results to the diff, if codespell doesn't have a way to do that.

2020-11-20 00:03 UTC, luzpaz commented
> The trouble with running it in CI is that there are a lot of false positives; I'm sure @luzpaz had to spend a while cherry picking the bits that are actually errors.
> Possibly we could use reviewdog to limit the results to the diff, if codespell doesn't have a way to do that.

Indeed. But each time I added them to  to the `-L` flag list. Codespell can be run specifically on the diff. I've seen it but not remembering exactly now.

2020-11-21 18:21 UTC, tacaswell requested changes
I agree with @QuLogic 's comment about `CureveLinear` vs `Curvilinear`.  For better or worse the class name is `CurveLinear` and we should match that in the text.

Anyone can clear this review.

2020-11-21 18:21 UTC, tacaswell commented on examples/axisartist/demo_curvelinear_grid2.py
> +Demo Curvilinear Grid2
```suggestion
Demo CurveLinear Grid2
```

2020-11-21 18:21 UTC, tacaswell commented on tutorials/toolkits/axisartist.py
> +   Demo Curvilinear Grid
```suggestion
   Demo CurveLinear Grid
```

2020-11-21 18:21 UTC, tacaswell commented on tutorials/toolkits/axisartist.py
> +   Demo Curvilinear Grid
```suggestion
   Demo CurveLinear Grid
```

2020-11-21 18:35 UTC, luzpaz commented
Added requested, thanks @tacaswell.  
+ rebased

2020-11-22 16:51 UTC, jklymak approved these changes

2020-11-22 21:32 UTC, timhoffm approved these changes

2020-11-22 21:33 UTC, merged

2020-11-22 21:34 UTC, timhoffm commented
Thanks @luzpaz!