CI: add github action to post to first-time PRs openers
matplotlib/matplotlib pull request #19166
Opened 2020-12-22 22:12 UTC by tacaswell

## PR Summary

Not sure how to test this?  

Below the line is how I think this should render:

--------

Thank you for opening your first PR into Matplotlib!

If you have not heard from us in a while please feel free to ping `@matplotlib/developers` or anyone who has commented on the PR.  Most of our reviewers are volunteers and it is easy for things to fall through the cracks.

You can also join us [on gitter](https://gitter.im/matplotlib/matplotlib) if real-time discussion would be useful.

For details on testing, write docs, and our review process please see [the developer guide](https://matplotlib.org/devdocs/devel/index.html)

We strive to be a welcoming and open project, please follow our [Code of Conduct](https://github.com/matplotlib/matplotlib/blob/master/CODE_OF_CONDUCT.md).

2020-12-22 22:37 UTC, story645 requested changes
Typo. But also where is the list this generates of PRs this would be applied to?

2020-12-22 22:37 UTC, story645 commented on .github/workflows/pr_welcom.yml
> +          For details on testing, write docs, and our review process
```suggestion
          For details on testing, writing docs, and our review process
```

2020-12-22 23:26 UTC, QuLogic commented on .github/workflows/pr_welcom.yml
> +name: PR Greetings
Typo in file name: `pr_welcom.yml`

2020-12-23 01:31 UTC, tacaswell commented
I do not think there is a list anyplace, this should run on any PR opened by a first-time contributor and leave the welcome message.

2020-12-23 02:53 UTC, ianhi commented
> Not sure how to test this?

Maybe merge this into your fork's default branch and then have someone open a PR against that?

Also this is a nice thing :+1: to is, especially to the explicit language making clear that it's ok to ping people if it lies dormant.

2020-12-23 02:55 UTC, ianhi commented
Maybe also include a mention of https://gitter.im/matplotlib/incubator? This seems like part of the audience you're trying to capture?

2020-12-23 12:40 UTC, timhoffm commented on .github/workflows/pr_welcome.yml
> +          PR.  Most of our reviewers are volunteers and it is easy for
```suggestion
          PR.  Most of our reviewers are volunteers and sometimes
```

Sounds a little more professional to me 😃 .

2020-12-23 12:40 UTC, timhoffm commented on .github/workflows/pr_welcome.yml
> +          discussion would be useful.
```suggestion
          gitter](https://gitter.im/matplotlib/matplotlib) for real-time
          discussion.
```

2020-12-23 16:13 UTC, story645 submitted a review, later dismissed

2020-12-23 17:52 UTC, jklymak approved these changes

2020-12-23 21:05 UTC, timhoffm approved these changes
Concerning testing, I'd just wait for the next new contributor and see if the action triggers properly. :smile:

2020-12-23 21:06 UTC, merged

2020-12-24 22:44 UTC, timhoffm commented
Ping @tacaswell : This does not work.

See e.g. #19172.

https://github.com/matplotlib/matplotlib/pull/19172/checks?check_run_id=1606582798

2020-12-25 01:57 UTC, tacaswell commented
I think I was too optomistic about the secrets already being set up.  I knew @QuLogic had set one up from the wheels but it looks like it is the wrong name for his to discover and I suspect has the permissions locked down enough that it would not work anyway...

2020-12-25 02:10 UTC, tacaswell commented
xref https://github.com/actions/first-interaction/issues/10

I'm now confused if we can actually make this work?  If it needs access to a secret to post, then that means the secret needs to be available to the PR, which means it is extract able via a malicious PR that adds a task to print out said secret, which means we can not give the action access to the secret, which means the action can not post back to the thread :facepalm: .

2020-12-25 03:10 UTC, jklymak commented
I thought this was an email to the user, not posted to the PR.

2020-12-25 19:24 UTC, ufmayer commented
On my first PR to the matplotlib project I did not receive a welcome email, instead my CI build failed. Digging through the logs I found a reference to the welcome message for first-time contributors as a FAIL during the build. It's posted on that PR #19172 that @timhoffm already linked above in this discussion.

2020-12-25 20:16 UTC, jklymak commented
@ufmayer Ooops, sorry we made you the guinea pig! This was something new we were trying.  Hopefully it is working now.

2020-12-25 21:06 UTC, ufmayer commented
No problem. If I can help out here let me know, but I guess I can make my first PR only once, and that's done for.

2020-12-29 16:35 UTC, jklymak commented
The welcome message is still not working?  

https://github.com/matplotlib/matplotlib/pull/19187/checks?check_run_id=1619669692

2020-12-29 21:07 UTC, dopplershift commented
Tried to fix it, see #19196.