Pin to oldest supported PyQt on minver CI instance.
matplotlib/matplotlib pull request #19317
Opened 2021-01-18 10:43 UTC by anntzer

This will be relevant once we also include PyQt6 support, as details of
enum access have changed in PyQt 5.11 (#19255).

PyQt is not actually a dependency so I don't think we can use the
constraints file (minver.txt) for that.

## PR Summary

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

2021-01-18 21:10 UTC, timhoffm approved these changes

2021-01-18 23:12 UTC, QuLogic commented
However,
> PyQt5 is not available

2021-01-19 00:50 UTC, QuLogic requested changes
This disables Qt5 tests entirely.

2021-01-19 10:41 UTC, anntzer commented
looks like I need to pin sip too, let's give that a try...

2021-01-19 18:12 UTC, anntzer commented
Indeed, this looks now fixed.

2021-01-20 01:05 UTC, QuLogic approved these changes

2021-01-20 01:06 UTC, merged