Minor cleanup of documentation guide
matplotlib/matplotlib pull request #19756
Opened 2021-03-21 22:58 UTC by timhoffm

## PR Summary

- shorten `.. literalinclude:` example
- link to Sphinx inheritance-diagram docs instead of explaining it ourselves
- remove emacs helpers. IMHO this is not relevant enough to justify additional clutter. (But hard-core emacs users may object).

2021-03-22 02:24 UTC, jklymak approved these changes
Looks good to me, but I dare not merge in case someone gets mad about the emacs helpers ;-)

2021-03-22 22:31 UTC, QuLogic requested changes
I don't know what `numpy_raster.txt` is, but I doubt it should be added.

2021-03-23 23:01 UTC, timhoffm commented
Whoops. I somehow have to get rid of the auto-add in git. Fixed.

2021-03-23 23:55 UTC, QuLogic approved these changes

2021-03-23 23:55 UTC, merged