Deprecate matplotlib.test()
matplotlib/matplotlib pull request #20586
Opened 2021-07-06 21:02 UTC by timhoffm

This is not a function that can be easily executed by the end user with a standard setup.  Testing requires substantial setup such as installing additional dependencies and reference data.  A function `matplotlib.test()` gives the false impression that a user can simply call it to verify if Matplotlib is working correctly.  Running pytest explicitly has become a de-facto standard and allows users to customize the run by various command line arguments.  There is no point in having a second own and more limited entry point to tests.

2021-07-06 22:26 UTC, tacaswell commented
I think we need this function to be able to run the tests against a "proper" install rather than a source install.  IIRC @QuLogic uses this in the fedora packaging.

2021-07-06 22:27 UTC, tacaswell requested changes
I think we need this to support testing installed versions (primarily to support the packagers).  @QuLogic can dismiss this with prejudice if I am wrong.

2021-07-06 22:48 UTC, timhoffm commented
Maybe it's my ignorance on the topic, I would have thought that proper install or editable install doesn't make a difference for testing. But happy to learn something new.

If this is only needed for packagers, we could still make it private and/or move it to `matplotlib.testing`. A top-level `matplotlib.test()` seems too prominent.

2021-07-06 22:48 UTC, QuLogic commented
I don't use it directly, but through `tests.py`. But as that's basically a wrapper around pytest, I think it should be possible to switch to it.

You should also confirm what happens on Debian, vv @sandrotosi

2021-07-06 22:53 UTC, tacaswell commented
> Maybe it's my ignorance on the topic, I would have thought that proper install or editable install doesn't make a difference for testing. But happy to learn something new.

There are some difficulties in how pytest auto-discovery works if you naively run the `pytest` CLI tool in the source tree (see discussion in https://github.com/matplotlib/matplotlib/issues/20312) with Matplotlib "properly" installed.

2021-07-06 23:08 UTC, timhoffm commented
Ah, might have to do with the test files being part of the package? I have to admit, that I have never really understood how pytest sets up the environment.

2021-07-06 23:24 UTC, tacaswell commented
>  I have to admit, that I have never really understood how pytest sets up the environment.

pytest is very magical (which is both the best and worst thing about it!).

2021-07-06 23:25 UTC, QuLogic commented
No, not really, you just have to ensure that `PYTHONPATH` points to a complete copy, and pass `--pyargs`, which is what `test` does.

2021-07-06 23:32 UTC, tacaswell commented
It also does extensive dependancy injection and re-writes the byte code!

2021-07-07 02:13 UTC, sandrotosi commented
> I don't use it directly, but through `tests.py`. But as that's basically a wrapper around pytest, I think it should be possible to switch to it.
> 
> You should also confirm what happens on Debian, cc @sandrotosi

yep, Debian does the same (thanks for checking!)

2021-08-21 07:56 UTC, QuLogic commented
I've switched Fedora to use `pytest` directly, so this is okay to do from its point of view. The only annoyance was that it had to use `--pyargs mpl_toolkits.tests` instead of plain `mpl_toolkits` because it's a namespace.

2021-08-21 22:00 UTC, timhoffm commented
@QuLogic thanks for checking! Could you amend the deprecation notice with your findings to prevent any stumbling blocks? I'm not sure what needs to be explained so that current `matplotib.test()` users can switch seamlessly.

This is not urgent. We can push this to 3.6 if there is too much 3.5 stuff still to do.

2021-08-24 00:27 UTC, QuLogic approved these changes
I'm okay with this, though I wrote some of the API change note.

2021-08-24 02:45 UTC, tacaswell approved these changes

2021-08-24 02:45 UTC, merged