Deprecate many single-use rc validators.
matplotlib/matplotlib pull request #21054
Opened 2021-09-12 12:42 UTC by anntzer

They can all easily be defined inline at the place of use.

## PR Summary

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

2021-09-12 18:48 UTC, timhoffm requested changes
Let's defer this to after the 3.5 release. I intend to start a general discussion on configuration handling for 3.6, an this deprecation may or may not match with its result.

I'll block to prevent accidential merging.

2021-09-14 08:28 UTC, anntzer commented
Sure, no worries.

2023-06-07 20:16 UTC, anntzer commented
Let's just close this then.

2023-06-07 20:16 UTC, closed without merging

2023-06-08 00:19 UTC, timhoffm commented
Note: #26088 now uses the validators as is. But we may change that later.