Bind subplot_tool more closely to target figure.
matplotlib/matplotlib pull request #21681
Opened 2021-11-19 19:41 UTC by anntzer

- More the implementation to backend_bases and have pyplot read it,
  rather than having backend_bases fetch it from pyplot, which was a
  bit weird.
- Attach the subplot_tool to the toolbar, which avoids having to keep
  a reference to it (when calling plt.subplot_tool), and prevents
  opening two subplot_tools for the same figure.  On most backends,
  closing the subplot_tool deletes the reference, because reopening a
  closed figure seems not guaranteed to work; on Qt, which has its own
  subplot_tool, reopening the closed QDialog does work, so just reuse
  it.
- Ensure that closing the main figure also closes the subplot_tool.
  (#21679, the main motivation for this PR.)

## PR Summary

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

2021-11-19 22:50 UTC, QuLogic approved these changes
You sniped me on this PR!

2021-11-20 00:23 UTC, greglucas requested changes
When I click on the subplot tool using the qt5agg backend, it immediately looks like it clears the figure. Somehow the values for the left/right adjustment are getting set to near zero.
![image](https://user-images.githubusercontent.com/12417828/142706481-6487a35b-9097-466a-8909-67f282717f1b.png)

I combined this with #21663 and it worked like a charm on the macosx backend!

One other request would be to add a test for this. Something that adds the subplot adjust window, then closes the main figure and asserts there is nothing left in the manager so we can be sure we're keeping this behavior in the future.

2021-11-20 09:49 UTC, anntzer commented
Fixed the bug with qt.
Testing is not completely trivial, because the toolwindow is explicitly *not* registered with Gcf so that one cannot e.g. make it the current figure (that wouldn't make sense), so it's just hanging off the toolbar and there isn't anything left to test once it's gone.  But if you can suggest a test implementation, please add it :-)

2021-11-20 14:02 UTC, greglucas approved these changes
Yeah, there were no tests before, so this is fine if there is not a trivial way of doing it. I just tested with macosx and qt5agg and it works as expected for me now.

2021-11-20 14:02 UTC, merged

2021-11-23 09:30 UTC, QuLogic commented
@meeseeksdev backport to v3.5.x