Added docstring to rrulewrapper class
matplotlib/matplotlib pull request #21993
Opened 2021-12-17 11:24 UTC by sveneschlbeck

#21880 @StefRe

2021-12-17 13:30 UTC, StefRe commented
hm, the docstring alone doesn't appear to have any effect - see [here](https://65597-1385122-gh.circle-artifacts.com/0/doc/build/html/api/dates_api.html) and [here](https://65597-1385122-gh.circle-artifacts.com/0/doc/build/html/gallery/ticks/date_formatters_locators.html).

2021-12-17 16:47 UTC, jklymak commented on lib/matplotlib/dates.py
> +    arbitrary date tick specifications.
Maybe "allowing flexible date tick ...".

2021-12-21 10:52 UTC, dstansby requested changes
Thanks for the PR! It looks like it's failing our flake8 tests. Could you fix this? It looks like there just a blank line that needs deleting.

2021-12-21 11:09 UTC, sveneschlbeck commented
@dstansby Thanks for the hint!

2021-12-21 11:22 UTC, dstansby approved these changes

2021-12-21 14:34 UTC, timhoffm approved these changes

2021-12-21 14:34 UTC, merged