Fix keyboard event routing in Tk backend (fixes #13484, #14081, and #22028)
matplotlib/matplotlib pull request #22077
Opened 2022-01-01 23:08 UTC by daniilS

## PR Summary
Currently, when using the Tk backend, Matplotlib sets the focus to the figure canvas upon its creation, as this is required to process keyboard events. As reported in #14081, this takes away the focus from other widgets when embedding a plot in a tkinter GUI, which creating a widget should never do (though the issue of other widgets being unable to take back the focus [was fixed in Tk 8.6.11](https://github.com/tcltk/tk/commit/b36fe5790a29cf78c58ab273cce93ab0604076ba)). Since a recent Python/Tk update, the focus doesn't get set to the canvas at all (#22028), though I cannot reproduce this outside of Matplotlib so can't tell what exactly caused this regression. Finally, the canvas has no visual indicator of having the focus, which makes it hard to get it to accept keyboard events again after tabbing out (#13484).

In this PR, the focus instead gets set to the canvas during the first call to `plt.show()`. It also gets set when the canvas receives a mouse click event, as is standard for widgets responding to keyboard events (e.g. entry widgets). 
- For pyplot windows, this fixes the regression from #22028, and shouldn't behave any different apart from that
- For embedded plots, this no longer steals the focus from other tkinter widgets, and the focus can instead be set by clicking the plot (or via `canvas.get_tk_widget().focus_set()`), as with any other widget
- In both cases, it allows restoring the focus by clicking the canvas after tabbing out, or when dealing with multiple embedded plots.

I've also added a unit test, and updated the "embedding in tk" example to reflect this behaviour.

## PR Checklist

**Tests and Styling**
- [x] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [x] New features are documented, with examples if plot related.
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

2022-01-06 13:55 UTC, daniilS commented
Glad I added the test, looks like Tk is behaving differently on macOS. I'll need to set up a VM or see if I can get access to a Mac to figure out what exactly causes the failure.

2022-01-06 15:31 UTC, daniilS commented
Looks like on macOS, `focus_get` returns None when the popup window itself doesn't have the focus. Replacing it with `focus_lastfor` fixes this on my machine, let's see if it fixes the tests as well.

2022-01-07 02:18 UTC, richardsheridan requested changes
Thanks for the contribution!

The code and behavior of this patch are good, but the fact is that this is a breaking change for embedded users and we need to handle them appropriately. At a minimum the patch should be prominently featured in the release notes and _not_ backported. It would also be nice to explicitly document this somewhere besides the example, somewhere that we already contrast other backend-specific quirks.

It may also be appropriate to do some kind of depreciation period before applying it. I'm happy to patch my own app fairly quickly but it may be more trouble for others?

2022-01-07 13:11 UTC, daniilS commented
@richardsheridan thanks for your feedback! I agree that a note is definitely needed somewhere.

I was unsure initially about how much other embedded users rely on the current behaviour, as it's undocumented, different from what's expected from any other widget, and existing code should still work after the patch if an end user clicks the plot (which I was doing myself before I realised the canvas claimed the focus for itself). If we do go with a deprecation period, we should probably still add the `focus_set()` call in `show()` straight away, as an immediate fix for #22028. `get_tk_widget()` might be the best place to put a warning about the change.

2022-01-18 13:59 UTC, ebardie commented
This fixes #22255, and https://gitlab.com/eBardie/topplot/-/issues/46. Thanks @daniilS.

2022-01-22 19:54 UTC, daniilS commented
I've removed the backward-incompatible change that prevented the tk canvas from stealing the focus upon creation, and will submit a separate PR for that with proper deprecation, aimed at 3.6.0. For now, this just closes #22028, #13484, #22255, and [this issue on Discourse](https://discourse.matplotlib.org/t/textbox-widget-doesnt-work-on-one-of-my-windows-pc/22544). As it's just a fix now, I would propose it get included in 3.5.2.

2022-01-22 20:36 UTC, richardsheridan approved these changes
LGTM

2022-01-25 21:19 UTC, timhoffm approved these changes

2022-01-25 21:20 UTC, merged

2022-01-25 22:23 UTC, daniilS commented
@timhoffm thanks, think #22028 and #22255 can be closed now!