Prevent tooltips from overlapping buttons in NavigationToolbar2Tk (fixes issue mentioned in #22028)
matplotlib/matplotlib pull request #22078
Opened 2022-01-02 00:01 UTC by daniilS

## PR Summary
As mentioned in the comments of #22028, the tooltips for the navigation toolbar buttons in the Tk backend overlap the right side of the buttons (probably DPI/resolution dependent), as the x-offset is hardcoded. This makes the right half of the buttons unresponsive, as the tooltip is continuously being shown and hidden. This PR always makes the tooltip appear directly to the right of the button.
## PR Checklist

**Tests and Styling**
- [N/A] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [N/A] New features are documented, with examples if plot related.
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

2022-01-06 07:30 UTC, QuLogic approved these changes

2022-01-06 23:22 UTC, timhoffm requested changes
The change itself is fine.

Please do not merge the main branch into a PR. As far as I understand git that will cause problems when we backport this for 3.5.2, which would be the natural thing to do for this bugfix. If you need to take changes from main into account in your branch here, please rebase on main.

2022-01-06 23:53 UTC, daniilS commented
@timhoffm thanks, I've changed the merge into a rebase now. I'll do that for #22077 as well.

2022-01-06 23:56 UTC, QuLogic commented
> Please do not merge the main branch into a PR. As far as I understand git that will cause problems when we backport this for 3.5.2, which would be the natural thing to do for this bugfix. If you need to take changes from main into account in your branch here, please rebase on main.

This is not technically true. The backport uses the merge commit vs the previous `main` HEAD, and doesn't care about the commits within the PR. We could also have squash merged the PR, which would ignore all the commits as well.

However, we do prefer rebases over merges, especially for small singular commit PRs like this one.

2022-01-07 23:49 UTC, daniilS commented
The failing test looks unrelated to the change

2022-01-08 01:26 UTC, timhoffm approved these changes

2022-01-08 01:27 UTC, timhoffm commented
codecov sometimes does strange things. TBH I don't understand it either.

2022-01-08 01:27 UTC, merged

2022-01-08 01:27 UTC, QuLogic commented
I restarted the failing test, it isn't failing any more; codecov is correct, we don't test tooltips.