Fix loading user-defined icons for Qt plot window
matplotlib/matplotlib pull request #22135
Opened 2022-01-06 22:37 UTC by timhoffm

## PR Summary

Closes #22131.

I'll refrain from writing a test for this because that would be quite cumbersome. One can manually test the correctness be deleting one of the `_large` icons. Then the plot window falls back to the low-res version of that icon.
It's also unlike to break again, because the comment should make future authors aware that we have to have the fall back for user icons.

2022-01-07 00:31 UTC, QuLogic commented
This affects Tk as well, I think.

2022-01-07 18:45 UTC, oscargus commented
Yes, here:
https://github.com/matplotlib/matplotlib/blob/80d4e2387c23c1e12d05720ae7375b7ac41fe24d/lib/matplotlib/backends/_backend_tk.py#L647-L649

2022-01-07 20:47 UTC, daniilS commented
I've copied the changes to the Tk backend in #22147

2022-01-07 21:51 UTC, QuLogic commented on lib/matplotlib/backends/backend_qt.py
> +            filepath = cbook._get_data_path('images', name)
```suggestion
            filepath = filepath.with_name(name)
```

2022-01-07 22:04 UTC, tacaswell approved these changes
I am also in favor of @QuLogic 's suggestion, but OK to merge either way.

2022-01-07 23:31 UTC, QuLogic approved these changes

2022-01-07 23:32 UTC, timhoffm commented
Thanks, I found a cleaner way of doing the due to @QuLogic's suggestion and @daniilS's PR for Tk (#22147).

2022-01-08 00:23 UTC, daniilS requested changes

2022-01-08 00:23 UTC, daniilS commented on lib/matplotlib/backends/backend_qt.py
> +        path_large = path_regular.with_name(name.replace('.png', '_large.png'))
`with_name` only accepts a new `name` as an argument
```suggestion
        path_large = path_regular.with_name(
            path_regular.name.replace('.png', '_large.png'))
```

2022-01-08 01:08 UTC, timhoffm commented on lib/matplotlib/backends/backend_qt.py
> +        path_large = path_regular.with_name(name.replace('.png', '_large.png'))
@daniilS Thanks!

2022-01-08 06:52 UTC, merged