ENH: MacOSX backend to use sRGB instead of GenericRGB colorspace
matplotlib/matplotlib pull request #22639
Opened 2022-03-12 14:47 UTC by remia

## PR Summary

Closes #22638.

2022-03-12 18:36 UTC, greglucas approved these changes

2022-03-13 10:29 UTC, dstansby requested changes
Looks 👍 to me, but could you put a quick note about the change in `matplotlib/doc/api/next_api_changes/behaviour` just so we have this documented.

2022-03-13 15:00 UTC, remia commented
Added the behavior note. I can also confirm I tested that locally and it behaves as expected.

2022-03-13 15:09 UTC, dstansby approved these changes

2022-03-13 16:13 UTC, greglucas commented
:tada: Thanks, @remia! Hope to see you contributing again.

2022-03-13 16:13 UTC, merged