FIX: completely remove QuadMesh cursor data
matplotlib/matplotlib pull request #22691
Opened 2022-03-23 21:42 UTC by jklymak

## PR Summary

Closes #22520

#19908 made using a mouse over large pcolormesh unusably slow.  

https://github.com/matplotlib/matplotlib/pull/22254 attempted to make this togglable with short circuit.  

Despite the changes in #22254, pcolormesh is still _really_ slow if you try and move a mouse around.  I actually do not understand why this is the case, because the short circuit in #22254 is actually called.  However, I'll put the onus of understanding the problem on the folks who want the cursor data, and I think we should pull this out for now. 

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

2022-03-23 23:05 UTC, tacaswell commented on doc/api/next_api_changes/behavior/22691-JMK.rst
> +`.QuadMesh.get_cursor_data`, introduced in 3.5.1 is unreasonably slow for
```suggestion
`.QuadMesh.get_cursor_data`, introduced in 3.5 is unreasonably slow for
```

2022-03-23 23:18 UTC, anntzer commented
#22693 works for me; can you confirm?

2022-03-23 23:19 UTC, anntzer requested changes
Let's consider #22693 first?

2022-03-24 09:32 UTC, anntzer commented on doc/api/next_api_changes/behavior/22691-JMK.rst
> +by default `.QuadMesh.set_mouseover` defaults to *False*.
"default" is repeated twice.

2022-03-24 09:32 UTC, anntzer approved these changes
Perhaps less than optimal wording in the changes note, but otherwise lgtm.

2022-03-24 23:05 UTC, tacaswell approved these changes

2022-03-24 23:06 UTC, merged

2022-03-25 02:36 UTC, QuLogic commented
Something seems off with meeseeks.

2022-03-25 02:49 UTC, QuLogic commented
@meeseeksdev backport to v3.5.x

For some reason, it thought this was closed and not merged.