Stairsplottype
matplotlib/matplotlib pull request #23311
Opened 2022-06-20 21:27 UTC by kkoutris

## PR Summary

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
Add stairs plot type to the documentation as asked from #23204

2022-06-21 08:15 UTC, jklymak requested changes
Thanks for this!

OTOH I don't think we should have both `stairs` and `steps`.  This should also be accompanied by a change to the cheatsheet if the `stairs` is really the preferred grammar here.

2022-06-21 08:15 UTC, jklymak commented on examples/text_labels_and_annotations/angle_annotation.py
> +                                          [10, 3.5, 11.4, 4])
Unrelated change?

2022-06-21 08:15 UTC, jklymak commented on plot_types/basic/stairs.py
> +==========
Docs won't build if formatting is incorrect: `/home/circleci/project/doc/plot_types/basic/stairs.rst:24: WARNING: Title overline too short.`
```suggestion
============
stairs(x, y)
============
```

2022-06-21 08:15 UTC, jklymak commented on plot_types/basic/stairs.py
> +plt.show()
We need the extra line for our linting.

2022-06-23 08:37 UTC, jklymak commented
I'll move to draft for now - feel free to move to ready when you have a chance to address..

2023-08-10 23:22 UTC, QuLogic commented
I think this has been replaced by #26233. Thank you for your effort @kkoutris; we're sorry that this was not accepted, but we hope to hear from you again.

2023-08-10 23:22 UTC, closed without merging