Add explicit registration of units in examples
matplotlib/matplotlib pull request #23508
Opened 2022-07-28 22:54 UTC by QuLogic

## PR Summary

Starting in https://github.com/sphinx-gallery/sphinx-gallery/pull/890, sphinx-gallery started clearing Matplotlib's unit registry. But since `basic_units` was already imported, its register-on-import never happened for subsequent examples, breaking them.

## PR Checklist

**Tests and Styling**
- [n/a] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [x] New features are documented, with examples if plot related.
- [n/a] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

2022-07-29 00:11 UTC, story645 approved these changes

2022-07-29 01:38 UTC, jklymak commented on examples/units/basic_units.py
> +def register_units():
I'm still a little tan about who is incorrect here.  It really seems sphinx gallery should spawn a new process for each example so the import happens again.  However, I can see why that would be slow.  It does make me extremely suspicious about changing behaviour via a registry that gets set at import time like this... (and yes we do it internally for dates and categorical as well).

2022-07-29 13:26 UTC, tacaswell requested changes
I think I see a better path using https://sphinx-gallery.github.io/stable/advanced.html#resetting-before-each-example

2022-07-30 00:24 UTC, QuLogic commented
Replaced by #23514.

2022-07-30 00:24 UTC, closed without merging