make.bat: Don't override SPHINXOPTS/O from the environment
matplotlib/matplotlib pull request #23634
Opened 2022-08-15 22:34 UTC by QuLogic

## PR Summary

I have not actually tested this... cc @story645

`if defined` does require command extensions to be enabled, but a) they're enabled by default, and b) we need them for `%~dp0` above already.

Fixes #23622 

## PR Checklist

**Tests and Styling**
- [n/a] Has pytest style unit tests (and `pytest` passes).
- [n/a] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [n/a] New features are documented, with examples if plot related.
- [n/a] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

2022-08-15 22:38 UTC, story645 requested changes

2022-08-15 22:38 UTC, story645 commented on doc/make.bat
>  set SPHINXOPTS=-W
if we'
```suggestion
set SPHINXOPTS=-W --keep-building
```
that's what the docs say is the default and that's what's set in the makefile

2022-08-15 23:12 UTC, story645 commented
this seems to work and is I think more direct:
```bat
if not defined SPHINXOPTS (
set SPHINXOPTS=-W --keep-going
)
```
but in both versions `SPHINXOPTS=` is overwritten, but `SPHINXOPTS=''" isn't so we should probably just put that in the docs?

2022-08-15 23:33 UTC, QuLogic commented
I didn't use `not defined` because that didn't appear to be specified in the docs: https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/if

Does `set SPHINXOPTS=` set a variable empty, or undefine it in Windows? Are you setting it in the environment or passing it at the end of the `make.bat` call?

2022-08-15 23:58 UTC, story645 commented
not is specified as optionally usable with a parameter and I haven't found anything that says it wouldn't work,  but also I won't block on that🤷‍♀️ 
> if [not] ERRORLEVEL <number> <command> [else <expression>]

> Does set SPHINXOPTS= set a variable empty, or undefine it in Windows? 

I think undefines it: 

```bat
>set SPHINXOPTS=        
>echo %SPHINXOPTS%
%SPHINXOPTS%
```

>Are you setting it in the environment or passing it at the end of the make.bat call? 

tried both

2022-08-16 20:36 UTC, story645 commented
Ok so putting at end doesn't work, put in a quick PR so docs reflect current state of build #23640 but once this PR works I think the docs get amended such that https://github.com/matplotlib/matplotlib/blob/9f5c041158024733c68fbc15eaee57cbe97fdab7/doc/devel/documenting_mpl.rst?plain=1#L100 becomes
```
> On Windows, set the options as environment variables, e.g.:
```bat
set O=-W --keep-going -j4 & make html
```

2022-08-16 22:20 UTC, story645 approved these changes
the .bat file seems to work now

2022-08-17 00:08 UTC, QuLogic commented
I don't mind committing here, just not the default commit message.

2022-08-19 19:27 UTC, merged