Handle rasterization start & stop only from Artist
matplotlib/matplotlib pull request #24293
Opened 2022-10-28 14:23 UTC by xerus

## PR Summary

As mentionedd in 3.4.0 api changes behaviour.rst the tracking should be handled there.

This commit avoids calling stop_rasterizing method twice in row making it throw an exception.

Fixes #24235

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [N/A] New plotting related features are documented with examples.

**Release Notes**
- [N/A] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [N/A] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [N/A] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

2022-10-28 14:52 UTC, oscargus commented
Thanks! Can you please add a test that fails in current main, but passes with this? (Probably similar to the example in https://github.com/matplotlib/matplotlib/issues/24235 but possibly shorter.) 

Not sure if this only happens for PDF files, but if that is the best way you can probably write to a buffer rather than stating a file name and make clear that it is a smoke test with a comment like `# smoke test for GH#24235`.

2022-10-28 17:24 UTC, tacaswell commented
This is not the correct fix as it eliminates the functionality of resterizing all artists below a given zorder.

2022-10-28 17:26 UTC, tacaswell requested changes
While this does fix the reported issue, it eliminates another functionality.

2022-10-28 17:42 UTC, tacaswell commented
The correct fix is to pull the depth counting logic from https://github.com/matplotlib/matplotlib/blob/d85e980f17bb64b131fea8356ce191d8db83472f/lib/matplotlib/artist.py#L24-L64 and re-implement it here.  I do not think we can directly use that wrapper as it does some extra stuff with the arists and `agg_filter` that we do not want here and a refactoring of the depth counting code that would compose the correct way with the other logic an that wrapper is not worth the complexity for avoiding 2 copies of like 10 lines of code.

Probably should also move the `start_rasterizing` and `stop_rasterizing` closer together so we can put the later in a `finally`.

2022-12-22 07:15 UTC, QuLogic commented
I believe this has been replaced by #24768.

2022-12-22 07:15 UTC, closed without merging