Add parameter type (links) for mpl_toolkits
matplotlib/matplotlib pull request #24860
Opened 2023-01-01 12:04 UTC by oscargus

## PR Summary

Related to https://github.com/matplotlib/matplotlib/issues/24859

## PR Checklist

**Documentation and Tests**
- [ ] Has pytest style unit tests (and `pytest` passes)
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] New plotting related features are documented with examples.

**Release Notes**
- [ ] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ ] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

2023-01-03 18:06 UTC, ksunden approved these changes

2023-01-03 20:30 UTC, timhoffm commented
Have you considered using :ref: rather than :doc:? https://github.com/matplotlib/matplotlib/issues/24859#issuecomment-1368579653

2023-01-26 12:44 UTC, dstansby requested changes
I agree with the comment @timhoffm linked above, that using `:ref:` is better than using `:doc:`, so I'll mark as requesting changes.

2025-09-15 13:41 UTC, timhoffm commented
Superseeded by #27200.

2025-09-15 13:41 UTC, closed without merging