Expire deprecations from 3.6
matplotlib/matplotlib pull request #24984
Opened 2023-01-14 13:39 UTC by oscargus

## PR Summary

Not all, but most (all?) of the ones I understood (quite) easily...

Split into multiple commits for somewhat sensible commit messages. Will add an api-change note.

## PR Checklist

**Documentation and Tests**
- [ ] Has pytest style unit tests (and `pytest` passes)
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] New plotting related features are documented with examples.

**Release Notes**
- [ ] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ ] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

2023-01-14 17:20 UTC, oscargus commented on doc/users/prev_whats_new/dflt_style_changes.rst
> -           ax_bottom.add_artist(mpatches.RegularPolygon(grid[3], 5, 0.1))
One would have expected this to warn earlier?

2023-01-16 00:08 UTC, efiring commented
Thank you for doing this.  I read through the file diffs without finding any problems.  I did not try to match every removal with a note in the changes/removals file, but I did notice that removals from the backends don't seem to be mentioned there.

2023-01-16 09:50 UTC, oscargus commented
Ahh, you are correct. Well spotted!

In the 3.6 documents it was a big list of all the backend changes, but I didn't touch the interactive ones, so at the time I just skipped that for later and forgot about it...

2023-01-16 09:55 UTC, oscargus commented
This is now added. 

Note that some of the things didn't have deprecation notices in the 3.6 docs, such as positional argument renaming.

2023-03-05 19:50 UTC, anntzer commented on doc/api/next_api_changes/removals/24984-OG.rst
> +so the ````Axes.get_renderer_cache`` method is removed. The
quadruple backquote

2023-03-05 20:07 UTC, anntzer commented on lib/matplotlib/mlab.py
>      ----------
You can probably at least remove the SO links (which predate sliding_window_view); FWIW I would just get rid of the entire function and inline it into _spectral_helper (and this way you only need to check once that noverlap < NFFT).

2023-03-05 20:21 UTC, anntzer commented on lib/mpl_toolkits/mplot3d/axis3d.py
>      def _set_pane_pos(self, xys):
You can inline _set_pane_pos to its only call site too (as I did at https://github.com/matplotlib/matplotlib/pull/25373/files#diff-ea1dd4bc7c3b7c0078e69e41e916d25354864e4f2fe31fd71210477f6f9f9660R310; note in particular that the staleness-setting in _set_pane_pos is redundant as we should be in the middle of a draw and thus clearing staleness right now.

2023-03-06 09:28 UTC, oscargus commented
Thanks @anntzer ! Should be sorted out now.

2023-03-06 09:40 UTC, anntzer approved these changes
postci

2023-03-06 19:07 UTC, ksunden commented on lib/matplotlib/collections.py
> +        if not isinstance(pickradius, Number):
Do we want this check to be for `Real` instead of `Number`?

2023-03-06 19:08 UTC, ksunden commented on lib/matplotlib/collections.py
> +        if not isinstance(pickradius, Number):
and should this also include a non-negative check like pickradius for Line2D?

2023-03-06 19:11 UTC, ksunden commented on lib/matplotlib/offsetbox.py
> +    def __init__(self, offsetbox, xy, *,
`*` should be after `xybox`, as `xycoords` was the indicated parameter

2023-03-06 20:35 UTC, ksunden requested changes
Only hard blocker is the offsetbox kw-only arg position, but also commented on collections version of `pickradius` if you wish to make that consistent with some other pickradus implementations

2023-03-07 09:08 UTC, oscargus commented
Thanks @ksunden ! Good finds!

2023-03-08 21:11 UTC, merged