Made changes to axis
matplotlib/matplotlib pull request #25060
Opened 2023-01-22 19:44 UTC by shadow-smoke

## PR Summary

Changed axis get tick positions. A bug caused "unknown" positions after moving ticks to the top right or the top left

## PR Checklist

**Documentation and Tests**
- [ N/A] Has pytest style unit tests (and `pytest` passes)
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] New plotting related features are documented with examples.

**Release Notes**
- [ ] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ ] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

2023-01-23 18:57 UTC, ksunden commented
The `'top', 'bottom'...` kwargs are intended to control the ticks themselves, not their labels or associated text.

You probably want `'labeltop', 'labelbottom', ...` which are translated into the already handled case where `label[12]On` get set as appropriate.

2023-01-24 01:02 UTC, QuLogic requested changes
A test or example of what is the bug is needed.

2023-01-27 14:50 UTC, rcomer commented
@shadow-smoke thank you for your contribution.  If you edit your original message and add "Fixes #21337" somewhere there, then the issue will automatically be linked to this pull request.  The link doesn't work in the title.

This will also need some tests that would have failed without the change, but now pass.

I'm going to mark this as "draft" for now.  Please mark it as "ready for review" when you are ready.  In the meantime, if you need help, feel free to ask questions here.  Or you may prefer to ask them in our [incubator gitter room](https://matplotlib.org/stable/devel/contributing.html#contributor-incubator).

2023-03-13 11:39 UTC, rcomer commented
I’m going to close this one as it has stalled for a while.

@shadow-smoke, please comment if you still want to work on this and we can re-open it.

2023-03-13 11:39 UTC, closed without merging