Plot directive preserve
matplotlib/matplotlib pull request #25091
Opened 2023-01-26 17:21 UTC by dstansby

## PR Summary
A rebase of https://github.com/matplotlib/matplotlib/pull/10149 onto current main, with conflicts solved, and the latest feedback on that PR taken into account. For context see the description of https://github.com/matplotlib/matplotlib/pull/10149.

## PR Checklist

**Documentation and Tests**
- [ ] Has pytest style unit tests (and `pytest` passes)
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] New plotting related features are documented with examples.

**Release Notes**
- [ ] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ ] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

2023-01-27 18:45 UTC, ksunden commented
How does this interact with the changes to the plot directive introduced in #24205?

My initial reaction is that the `outname` change should be orthogonal, but the `plot_cache_dir` may conflict and/or be totally ignored.

2023-01-27 19:43 UTC, tacaswell commented on doc/users/next_whats_new/sphinx_plot_preserve.rst
> +easy to understand which output image is which and, more importantly, uniquely
I am slightly skeptical of the first claim (that users can give things good names) and _very_ skeptical of the second as the name is not random, it is based on the name of the file (and the position + function of the directive in that file) so is structurally unique.  If users can control the names there is a high chance that they are going to collide.

If we want to make things save to cache like this we should give them names based on the hash of the source....

2023-01-27 19:48 UTC, tacaswell commented on lib/matplotlib/sphinxext/plot_directive.py
> +                    if config.plot_cache_dir and outname is not None:
We do not actually use `outname` for anything other than checking it exists!

2023-01-27 19:50 UTC, tacaswell requested changes
I have some conceptual concerns:
 - name are already (structurally) unique
 - do not trust users to give things unique names (although it does check that)
 - the cache is not invalidated if the code in the directive changes

and an implementation concern (we do not seem to actually use `outname` in the code!)

I think this is a good idea, but probably should cache the files based on a hash of the source rather than a user supplied name.

2023-01-27 20:44 UTC, dstansby commented
Sorry for doing a 'blind' rebase and not really thinking this through myself, but thanks for re-reviewing! Just thinking about the key for the cache, hasing the source code is potentially no though good because changes in Matplotlib internals (e.g. a change in default style, a bugfix to a plotting method) would lead to a different image with the same source code.

So I think we either have to:

1. Abandon this
2. Use a hash of the source code of the key, with some suitable user warning that any cached images will only ever be automatically updated if the source code is updated.

I'm torn between these two options, but am erring towards number 1. due to the potential of number 2. to cause comfusion to users at some point down the line. Thoughts?

2023-01-27 22:54 UTC, tacaswell commented
> Sorry for doing a 'blind' rebase and not really thinking this through myself, but thanks for re-reviewing! 

I went back to the original PR where I also did a blind rebase and am to blame for at least some of these issues!

For the key we could start the hash with `matplotlib.__version__`, but for developers that would quickly lead to an ~unbounded cache as we put the git sha in the version and would only move the problem out a level to any plot directive that uses Matplotlib via a library (e.g. seaborn) having exactly the same problem but not participating in the hash (and it seems this would be general to any library used in the code...).

So given the caching problem (nb: there are two hard problems in computer science: naming things, cache invalidation, and off-by-one bugs) I'm inclined to go with option 1 as well.

2023-01-30 09:46 UTC, dstansby commented
In that case I'll close. @r-barnes thanks a lot for opening this PR originally - we decided not to carry it forward because of the difficulties of caching the images. See the comment above this one for more context. I think we would be open to re-visiting this, but that would require a well thought out strategy for caching the images in an issue before opening a pull request.

2023-01-30 09:46 UTC, closed without merging