Remove nonfunctional Axes3D.set_frame_on and get_frame_on methods.
matplotlib/matplotlib pull request #25648
Opened 2023-04-08 08:08 UTC by saranti

## PR Summary
Fixes #24689. Remove `Axes3D.set_frame_on` and `get_frame_on` from the codebase and from the link in the documentation.

2023-04-08 09:51 UTC, timhoffm requested changes
I think we need to keep these functions and raise `NotImplementedError`, because by removing we would inherit the functionality from Axes, which does not work for 3D.

2023-04-09 04:58 UTC, saranti commented
> I think we need to keep these functions and raise `NotImplementedError`, because by removing we would inherit the functionality from Axes, which does not work for 3D.

Ok. The python docs state that `NotImplementedError` should not be used to indicate that an operator or method is not meant to be supported at all, but rather if the method is still being developed etc. Do you still want to go ahead with it? Do you have any more plans for this, like getting rid of the frame_on concept entirely?

2023-04-09 09:13 UTC, rcomer commented
From the docs, it looks like the recommended approach is to set the method to `None`.
https://docs.python.org/3/library/exceptions.html#NotImplementedError

2023-04-09 20:56 UTC, timhoffm commented
Setting to none (plus leaving a comment there) seems the right approach. Thanks for checking the meaning of NotImplementedError.

2023-04-10 07:07 UTC, rcomer commented
My understanding of the guidance is to set the actual method to `None`, rather than the return value.  I couldn’t find any examples by googling, but here is one I happen to know about in another project, where we wanted to disable the `__iter__` method.

https://github.com/SciTools/iris/blob/c74d78331aeb394383d1552e3d1679b0f734b402/lib/iris/cube.py#L2551-L2553

2023-04-25 10:49 UTC, oscargus commented
Sorry for not seeing this until now. Good that things were clarified in the meanwhile. I think a note in doc/api/next_api_changes/removals/ would be nice. Basically saying that they were not working and therefore removed. If nothing else we can point at it, in case someone reports an error later. Other than that, is should be good to go!

2023-04-25 13:43 UTC, oscargus approved these changes
@timhoffm can you please have a new look?

2023-04-25 23:43 UTC, timhoffm approved these changes

2023-04-25 23:47 UTC, merged