Allow option to display absolute values for pie chart #19338
matplotlib/matplotlib pull request #25757
Opened 2023-04-24 01:29 UTC by codebreakymefix

## PR Summary
Adds a parameter 'wedgelabels' to pie() for the user to display absolute or percent values in the wedges. Renamed 'autopct' to "wedgelabelsfmt" as the user requested. 
## PR Checklist

**Linked Issue**
- [ ] Added "closes #0000" in the PR description to link it to the original issue.

**Documentation and Tests**
- [ ] Has pytest style unit tests (and `pytest` passes)
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] New plotting related features are documented with examples.

**Release Notes**
- [ ] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ ] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

2023-04-24 12:17 UTC, oscargus requested changes
Thanks for this!

It is not clear to me how this works in practice. Right now, both `autofmt` and `wedgelabelsfmt` does the same thing? If so, why should we have both? If not, how can we deprecate `autofmt` later?

If it is only a matter of a "bad" name, then I think it is better to just have one name and use the decorator `@_api.rename_parameter("3.8", "autofmt", "wedgelabelsfmt")`.

However, I would wait for additional input before going all in on these changes. (New arguments after `*` is a requirement though.)

Edit: after reading the issue, I think it should be quite OK to add the decorator as well.

2023-04-24 12:17 UTC, oscargus commented on lib/matplotlib/axes/_axes.py
>              frame=False, rotatelabels=False, *, normalize=True, hatch=None):
The new arguments must be added after the `*` in case someone is using positional arguments.

2023-09-29 11:05 UTC, rcomer commented
Hi @codebreakymefix are you still interested in working in this?  It looks like maybe you were waiting for reviewers to reach a consensus.

I think I agree with @story645 on this that the proposed _wedgelabels_ could be confusing.  As the [pie example](https://matplotlib.org/stable/gallery/pie_and_polar_charts/pie_features.html#swap-label-and-autopct-text-positions) shows, the current _labels_ can be put on the wedge and the automatic percentage labels outside.

Perhaps _autolabels_ and _autolabelfmt_ rather than _wedge…_ might work?  Or I also like @story645’s suggestion of an “absolute” format keyword that can’t be passed together with _autopct_.

2023-10-15 17:18 UTC, rcomer commented
Discussion on parameter name also needs to consider the _pctdistance_ parameter.

2024-05-07 21:26 UTC, closed without merging