Add auto-scaling support to "add_collection3d"
matplotlib/matplotlib pull request #25751
Opened 2023-04-22 08:01 UTC by lganic

## PR Summary
closes #17130

Adds support for auto-scaling 3D collection objects in the add_collection3d function. The new implementation is consistent with the behavior of the existing 2D implementation, where auto-scaling is True by default.

Test cases were added for each of the relevant autoscaling functions. 

The autoscaling works with most 2D/3D collections; the only collection I wasn't able to get working was Patch3DCollection, which (as far as I can tell) seems to have a number of ongoing bugs that make them borderline unusable, and untestable. 

Also turns out that a few of the test cases suffered from the bug seen in #17130, so I updated the failing tests accordingly. 
## PR Checklist

**Linked Issue**
- [ ] Added "closes #0000" in the PR description to link it to the original issue.

**Documentation and Tests**
- [ ] Has pytest style unit tests (and `pytest` passes)
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] New plotting related features are documented with examples.

**Release Notes**
- [ ] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ ] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

2023-05-05 20:23 UTC, scottshambaugh commented
I believe this may also close https://github.com/matplotlib/matplotlib/issues/23317, and we should check if it helps https://github.com/matplotlib/matplotlib/issues/14298 as well.

2023-05-10 07:14 UTC, QuLogic requested changes
We would prefer if you could rebase instead of merge. It appears there are some completely unrelated commits in this PR that shouldn't be here.

2023-05-10 07:14 UTC, QuLogic commented on lib/mpl_toolkits/mplot3d/axes3d.py
> +            if type(col) is art3d.Line3DCollection:
Is there a reason to not use `isinstance` here?

2024-06-14 04:29 UTC, scottshambaugh commented
Hi @lganic, are you still interested in working on this PR?

2024-06-14 13:49 UTC, closed without merging