FIX: Handle masked arrays for RGBA input with ScalarMappables
matplotlib/matplotlib pull request #26096
Opened 2023-06-09 01:48 UTC by greglucas

## PR summary

Currently, the mask is ignored if a user passes in RGB(A) input arrays. This sets the alpha channel to 0 when any RGB(A) input is masked. This is relevant for RGB(A) data being used with pcolormesh. xref: https://github.com/SciTools/cartopy/pull/2166 where it will simplify downstream accounting for masks and alpha.

## PR checklist

- [n/a] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [n/a] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-examples-and-tutorials)
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) guidelines

2023-06-09 21:07 UTC, tacaswell requested changes
This needs an API change note.

I'm sure we have at least one user who is relying on the mask being ignored!

I do not think this needs a deprecation cycle (as I suspect "just document it" was to avoid fixing a bug).

2023-06-09 22:09 UTC, greglucas commented
:+1: Added a change note now.

2023-06-09 23:05 UTC, tacaswell approved these changes

2023-06-10 08:13 UTC, rcomer approved these changes
Thank you for doing this @greglucas!

I have also verified that it enables the hoped for simplification of my Cartopy branch.

2023-06-10 08:13 UTC, merged