Removed the deprecated code from axis.py
matplotlib/matplotlib pull request #26870
Opened 2023-09-22 17:30 UTC by agautam478

## PR summary
This PR removes the deprecated code from `lib/matplotlib/axis.py`  which is a sub issue in the parent issues here: https://github.com/matplotlib/matplotlib/issues/26865
-->
## PR checklist

- [ N/A] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ N/A] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [N/A ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [ N/A] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [N/A ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

2023-09-22 17:37 UTC, ksunden commented
https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.8.0.html#tick-set-label1-and-tick-set-label2

Here is the release note from the deprecation

2023-09-23 02:41 UTC, QuLogic reviewed
The documentation build also says that `doc/api/axis_api.rst` also contains some old references to these removed items.

2023-09-23 02:41 UTC, QuLogic commented on doc/api/next_api_changes/removals/26870-AG.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Should be more specific about location:
```suggestion
``matplotlib.axis.Tick.set_label1`` and ``matplotlib.axis.Tick.set_label2``
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2023-09-23 02:41 UTC, QuLogic requested changes
Also marking as request-changes so that this isn't merged before 3.9 is out.

2023-09-25 16:21 UTC, agautam478 commented
pre-commit.ci autofix

2024-04-27 00:13 UTC, QuLogic commented
Hi @agautam478; 3.9 is branched now, so this can go in. Do you mind rebasing so that the CI results will be current?

2024-09-18 20:56 UTC, ksunden commented
Thank you for your effort, however these changes got rolled into a larger deprecation commit in  #28183, so closing now.

2024-09-18 20:56 UTC, closed without merging