deprecated api tri
matplotlib/matplotlib pull request #26909
Opened 2023-09-25 10:51 UTC by vigneshvetrivel8

## PR summary
Helps with #26865 (lib/matplotlib/tri/*.py).
## PR checklist

- [ ] "closes #26865 (lib/matplotlib/tri/*.py)" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [ ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [ ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

2023-09-25 17:33 UTC, ksunden commented
The deprecation here is to remove the edited files entirely, as their contents/organization is now considered private (and thus they have `_tri<x>` python modules).

2023-09-25 23:13 UTC, QuLogic requested changes
This is not removing the deprecations, but changing imports in files that are deprecated, which does not achieve the desired result. In fact, it causes _more_ things to appear in the deprecated files.

2023-09-26 20:53 UTC, ksunden requested changes
Please do not edit the 00001-ABC.rst file, and instead make a new file e.g. `26909-VV.rst`

You can copy the contents (and update to reflect removal instead of deprecation) from, which gives more context and says what to do instead:

https://github.com/matplotlib/matplotlib/blob/d60de5ed4d374d688463a1a49684f6cd1dbdd0d5/doc/api/prev_api_changes/api_changes_3.7.0/deprecations.rst?plain=1#L81-L86

2023-09-27 20:27 UTC, QuLogic commented on doc/api/next_api_changes/removals/26909-VV.rst
> + available in ``matplotlib.tri`` directly and should be imported from there.
The indent makes it a code block, and doesn't get rendered as a heading:
```suggestion
``matplotlib.tri`` submodules are removed
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The ``matplotlib.tri.*`` submodules are removed.  All functionality is
available in ``matplotlib.tri`` directly and should be imported from there.
```

2023-09-29 13:39 UTC, vigneshvetrivel8 commented
Do i need to modify some more or is this enough. Is this PR ok.

2023-09-30 00:51 UTC, QuLogic approved these changes
This looks good, except for the pre-commit linting issue. I'm going to have it fix it automatically for you.

2023-09-30 00:51 UTC, QuLogic commented
pre-commit.ci autofix

2023-10-02 21:08 UTC, ksunden approved these changes

2023-10-02 21:08 UTC, merged

2023-10-03 07:48 UTC, QuLogic commented
Thanks @vigneshvetrivel8! Congratulations on your first PR to Matplotlib :tada: We hope to hear from you again.