#26865 removing deprecations to patches.py and axislines.py
matplotlib/matplotlib pull request #26900
Opened 2023-09-23 18:36 UTC by farrjere

## PR summary

This PR removes the depcrecated code during the version 3.7 from patches.py and axislines.py for the issue #26865 
## PR checklist

- [ NA] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ NA] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ NA] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [ NA] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [ NA] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

2023-09-25 12:27 UTC, oscargus reviewed
Thanks!

I think this is good, subject to updating the wording of the release note.

2023-09-25 12:27 UTC, oscargus commented on doc/api/next_api_changes/removals/26900-jf.rst
> +This attribute of ``AxisArtistHelper``\s is deprecated.
```suggestion
This attribute of ``AxisArtistHelper``\s is removed.
```

2023-09-25 12:27 UTC, oscargus commented on doc/api/next_api_changes/removals/26900-jf.rst
> +been deprecated.
```suggestion
been removed.
```

2023-09-25 13:06 UTC, farrjere commented on doc/api/next_api_changes/removals/26900-jf.rst
> +This attribute of ``AxisArtistHelper``\s is deprecated.
This has been updated.

2023-09-25 13:10 UTC, oscargus approved these changes

2023-09-25 13:12 UTC, oscargus commented
For a second reviewer: there is a PR open for patches, #26890, but this can go in as is, the other requires some updates.

2023-10-11 21:45 UTC, ksunden commented
We merged another PR that addressed the patches portions of this, @farrjere can you refocus this PR on only the axislines portion?

2023-10-17 17:34 UTC, ksunden commented on lib/matplotlib/patches.pyi
> +                self.x, self.y = xy
We do not wish to add this back, especially as this is a `pyi` stub file (where `@api.deprecated` has no effect)

2023-10-17 17:37 UTC, ksunden requested changes
Please revert changes to `patches.pyi`

2023-10-17 17:39 UTC, ksunden commented
Needs a rebase because an adjacent bit of code was modified (adding a new deprecation for the 3.9 cycle). That deprecation should be kept, but the removal of the `passthru_pt` attr should still happen.

2023-10-17 18:02 UTC, farrjere commented
Wouldn't handling the merge conflict handle that? I went to do this myself but it resulted in an issue with _version.py having a formatting issue that couldn't commit (coming from the merge).

2023-10-17 18:18 UTC, ksunden commented
Rebasing is our preferred method of handling merge conflicts.

`_version.py` should not be committed into the repo (it is a build artifact, and you are seeing it as a result of the change of build system #26621) I would suggest running `git clean -fdx` first (and reinstalling after updating to the meson-based branch).

The patch as submitted has additions to `patches.pyi`, which should not be included.

2023-10-18 01:20 UTC, ksunden approved these changes

2023-10-19 04:07 UTC, merged

2023-10-19 04:07 UTC, QuLogic commented
Thanks @farrjere! Congratulations on your first PR to Matplotlib :tada: We hope to hear from you again.