Add test_contour #26864
matplotlib/matplotlib pull request #27013
Opened 2023-10-06 08:49 UTC by kots14

## PR summary
Attempting adding code for `test_contour` method in `test_datetime.py` mentioned in [#26864](https://github.com/matplotlib/matplotlib/issues/26864)

**Image output -**
![test_datetime_contour](https://github.com/matplotlib/matplotlib/assets/20207952/644bdb80-a832-489a-af82-ddfc314c8d0d)

## PR checklist

- [x] resolves [#26864](https://github.com/matplotlib/matplotlib/issues/26864)
- [ ] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [ ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [ ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

2023-10-06 11:07 UTC, kots14 commented on lib/matplotlib/tests/test_datetime.py
> +        f = lambda x, y: np.cos(x / 4) + np.sin(y / 4)
I'll remove this in next revision since [this](https://github.com/matplotlib/matplotlib/actions/runs/6429513784/job/17458731096?pr=27013) is failing.

2023-12-05 20:36 UTC, QuLogic requested changes
I suppose the extra 3 Axes could be removed if you're making updates.

2023-12-05 20:36 UTC, QuLogic commented on lib/matplotlib/tests/test_datetime.py
> +    @mpl.style.context("default")
This old test should not be re-added.

2023-12-06 08:13 UTC, kots14 commented on lib/matplotlib/tests/test_datetime.py
> +    @mpl.style.context("default")
Oh, I'll modify this.

2023-12-06 08:14 UTC, kots14 commented
> I suppose the extra 3 Axes could be removed if you're making updates.

You mean from these lines shall I remove 3?
```
ax1.contour(X_dates, Y_dates, Z_timestamps)
ax2.contour(X_dates, Y_ranges, Z_timestamps)
ax3.contour(X_ranges, Y_dates, Z_timestamps)
bx1.contour(X_dates, Y_dates, Z_ranges)
bx2.contour(X_dates, Y_ranges, Z_ranges)
bx3.contour(X_ranges, Y_dates, Z_ranges)
```

2023-12-06 16:05 UTC, ksunden commented
The last three (and get rid of the variables that become unused as a result).

2023-12-12 08:22 UTC, QuLogic approved these changes

2023-12-12 09:28 UTC, merged

2023-12-12 09:28 UTC, QuLogic commented
Thanks @kots14! Congratulations on your first PR to Matplotlib :tada: We hope to hear from you again.