MNT: set codcov to ignore docs and galleries
matplotlib/matplotlib pull request #27071
Opened 2023-10-12 17:48 UTC by story645

No idea if this is the right way to do this and not sure how to check, but it's very confusing to have documentation prs fail on code cov.

2023-10-12 18:48 UTC, ksunden commented
I also think adding a `threshold: 0.5%` (or 1% or whatever level we wish to add) would greatly help reduce the number of red X's we get that most just ignore anyway.

I think this would go inside of the `default` entry? though have also have not looked too deeply at their config file format...

2023-10-17 19:34 UTC, tacaswell requested changes
Please do not ignore coverage changes to the test files.

2023-10-17 19:34 UTC, tacaswell commented on .github/codecov.yml
> +  - "test_*.py"
The coverage on the test files is probably the most important thing to measure.

2023-10-17 20:38 UTC, tacaswell commented on .github/codecov.yml
> +  - "test_*.py"
you can not run our complete test suite on a single machine due to the platform specific tests/code and optional dependencies.  These checks are critical to make sure we do not accidentally drop coverage do to changes in CI.

Put another way, tests test our code, but what tests the tests?  Verifying that your tests actually run is about the only thing we have that covers that need.

@dopplershift has also taken this position in the past.

2023-10-17 20:45 UTC, tacaswell commented
We have also seen issues where because we are feeding codecov from a bunch of different CI services they have the problem of deciding when they have received "enough" of the reports to be worth posting their report.  

For example, if we lose a windows job it can cause some tests (and code) to not be covered.  Sometimes CI has died / failed / upload errored out so it is never coming and sometimes it is just taking "too long" so we get a false-negative.

2024-05-02 16:06 UTC, closed without merging