Final remove
matplotlib/matplotlib pull request #27092
Opened 2023-10-14 15:04 UTC by Krrish2512

## PR summary
This PR removes the deprecated code during the version 3.7 from lib/matplotlib/gridspec.py and lib/matplotlib/_fontconfig_patterns.py
-->
## PR checklist

- [ ] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [-] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [ ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [ ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

2023-10-16 13:08 UTC, rcomer reviewed
Thank you for your contribution @Krrish2512!

The `gridspec` lines you removed are not actually deprecations, and the deprecations that were in that file were handled at #26885.

2023-10-16 13:08 UTC, rcomer commented on lib/matplotlib/_fontconfig_pattern.py
> -                continue
This should now raise an error.

2023-10-16 23:28 UTC, QuLogic requested changes
Too much code is removed, as noted by @rcomer.

2024-03-03 16:35 UTC, rcomer commented
I’m going to close this as #26865 is complete.

2024-03-03 16:35 UTC, closed without merging