Getter/Setter
matplotlib/matplotlib pull request #27116
Opened 2023-10-17 04:15 UTC by Arikad0

This is my first open source contribution to a project, hope it could be helpful, anything that I can improve on this PR, please contact me, any tips would be appreciated. This PR references to #24617.

2023-10-17 05:07 UTC, ksunden requested changes

2023-10-17 05:07 UTC, ksunden commented on lib/matplotlib/figure.py
> +    def set_subplot_params(self, subplot_params=None):
The getter and setter are inconsistent in `_subplotparams` or `_subplot_params`

Additionally, while I think the more spelled out name is _better_, the idea is I think to match the variable as in `__init__`, so they should probably be `[gs]et_subplotpars`, that or have the canonical as `[gs]et_subplotparams` and use `alias` to make `[gs]et_subplotpars` work as well.

I will note that the issue had the more spelled out name, admittedly.

2023-10-17 05:07 UTC, ksunden commented on lib/matplotlib/tests/test_figure.py
> +        setfunc = getattr(fig, f"set_{var}")
This test assumes all of #24617 is complete, which this PR as it stands does not accomplish, and so it is failing.

2023-10-17 05:07 UTC, ksunden commented on lib/matplotlib/tests/test_figure.py
> +    assert fig.subplotpars == fig.get_subplotparams()
This test is using `set_subplotparams` which is currently implemented as `set_subplot_params`, and so it is failing.

2023-10-18 21:52 UTC, closed without merging

2023-10-19 12:26 UTC, melissawm commented
Hi @Arikad0 - did you mean to close this?