Defined the test_clabel function in the test_datetime file
matplotlib/matplotlib pull request #27490
Opened 2023-12-10 01:39 UTC by AliAboelela123

## PR summary

This PR is one of the issues identified by the larger issue #26864. These changes add a test for the clabel function. I have tested passing datetimes as input labels to the contours. I could not think of a way nor do I think it to make sense to pass datetime objects as labels to either axis.

Here is the image generated by this code:

![download](https://github.com/matplotlib/matplotlib/assets/62535124/12254c67-6ef9-4e5f-b570-d88cb62766bc)

## PR checklist

- [N/A] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
I have struggled to run pytest due to a circular import issue. Instead, the image of the plot was generated using a separate script.

- [N/A] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [N/A] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [N/A] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

2023-12-10 01:45 UTC, jklymak commented
I think the test here is that the contour x and/or y axes are datetimes, and that the manual placement of clabels can be specified with datetimes.  I'm actually skeptical that this works, but if not, would be good to document it.

2023-12-10 01:47 UTC, AliAboelela123 commented
How would I be able to test this? How would I generate the values for Z if X and Y are datetime objects?

2023-12-10 05:37 UTC, jklymak commented
@AliAboelela123 I've not looked in detail, but it is possible to contour with `x`  or `y` as a datetime vector.  `z` should just be normal non-datetime data.  First, it would be madly useful to double check that `clabel` works at all for that case.  Second, `clabel` takes a `manual` kwarg, and the x, y version of that kwarg would ideally take datetime as the `x` value.  I'm not sure if it does or not.

2023-12-10 10:16 UTC, rcomer commented
One use-case for z datetimes is to plot a [map of monsoon onset](https://www.skymetweather.com/content/wp-content/uploads/2014/05/SW-MONSOON-FINAL.jpg), though I agree that having datetimes on the x- or y-axis is more common.  Perhaps it is worth testing both?

2023-12-10 10:22 UTC, rcomer commented
> I've tried a few different things but only ran into errors.

If the errors show that we don't currently support this, then that is useful information and part of what the issue is looking to find out.  So please post your findings :+1:

2023-12-10 13:15 UTC, AliAboelela123 commented
I've made some updates, I don't expect this to be merged soon but rather just trying to continue the conversation. I summarized my findings in an edit

2023-12-10 15:49 UTC, jklymak commented
@AliAboelela123 I still think you are misunderstanding. The x array should be datetime _before_ sending to contour.  Subsequently clabel should be called with the manual kwarg.

2023-12-10 15:51 UTC, jklymak commented
> Perhaps it is worth testing both

The z data in contour is not run through unit machinery, so all we would be testing is that clabel takes an arbitrary string.

2023-12-10 17:14 UTC, AliAboelela123 commented
Ok I've tried to fix the PR by constructing the contour using datetime objects and passing that as input to the clabel function. I have not used the manual kwarg though. Do the current changes more accurately reflect what this test suite is attempting to test?

2023-12-10 17:21 UTC, jklymak commented
> Subsequently clabel should be called with the manual kwarg.

> I have not used the manual kwarg though. Do the current changes more accurately reflect what this test suite is attempting to test?

No?  What are you not understanding about the "manual" kwarg?

2023-12-10 17:37 UTC, AliAboelela123 commented
`# Select specific x values
selected_x_values = [x[0], x[6], x[12], x[18]]
# Pair them with specific dates
selected_dates = [dates[0], dates[3], dates[6], dates[9]]
# Create pairs of (x, date)
manual = [(x_val, date) for x_val, date in zip(selected_x_values, selected_dates)]`

"TypeError: Cannot cast array data from dtype('O') to dtype('float64') according to the rule 'safe'"

This makes me think that the manual param expects the tuples to have float type i.e. coordinates in a plane. I'm not sure if I'm doing something wrong or if this is the intended limitation of the clabel function which we are attempting to document.

2023-12-10 17:38 UTC, AliAboelela123 commented
```
# Select specific x values
selected_x_values = [x[0], x[6], x[12], x[18]]

Pair them with specific dates
selected_dates = [dates[0], dates[3], dates[6], dates[9]]

Create pairs of (x, date)
manual = [(x_val, date) for x_val, date in zip(selected_x_values, selected_dates)
```

"TypeError: Cannot cast array data from dtype('O') to dtype('float64') according to the rule 'safe'"

This makes me think that the manual param expects the tuples to have float type i.e. coordinates in a plane. I'm not sure if I'm doing something wrong or if this is the intended limitation of the clabel function which we are attempting to document.

2023-12-10 17:39 UTC, AliAboelela123 commented
```
# Select specific x values
selected_x_values = [x[0], x[6], x[12], x[18]]

Pair them with specific dates
selected_dates = [dates[0], dates[3], dates[6], dates[9]]

Create pairs of (x, date)
manual = [(x_val, date) for x_val, date in zip(selected_x_values, selected_dates)
```
I tried to pass the above ^^ "manual" param to the clabel function but I get the following error:

"TypeError: Cannot cast array data from dtype('O') to dtype('float64') according to the rule 'safe'"

This makes me think that the manual param expects the tuples to have float type i.e. coordinates in a plane. I'm not sure if I'm doing something wrong or if this is the intended limitation of the clabel function which we are attempting to document.

2023-12-11 18:09 UTC, jklymak commented
I didn't test it myself, but if the manual clabel doesn't work then that would be a bug report issue.  Probably we should process the unit info for the clabel manual inputs.  

This PR could still test that labelling works when the x and y axis are datetimes.  Somewhat more trivial, but worth checking.

2023-12-16 00:16 UTC, QuLogic commented
I've opened #27525 for the `manual` argument of `clabel` not accepting units. This PR is possibly okay without testing that yet, but it currently has linting issues that need to be fixed.

2023-12-18 20:47 UTC, ksunden requested changes
I don't think the code as it is written here is exercising the datetimes at all really, it is only using them as labels (passed through `str`, not processed through our unit system)

I think that the `manual` behavior described in #27525 would be a good thing to test here, but that doesn't yet work

As for datetimes on the Z axis, we simply don't have any native support for that at this time, and that would be a larger change.

2024-09-13 19:20 UTC, closed without merging