Fix pickling of AxesWidgets.
matplotlib/matplotlib pull request #28430
Opened 2024-06-20 15:34 UTC by anntzer

There's no need to hold onto the (non-picklable) canvas as an attribute.

Closes #22482.

## PR summary

## PR checklist

- [ ] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [ ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [ ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

2024-06-21 03:30 UTC, QuLogic approved these changes

2024-06-26 19:21 UTC, ksunden approved these changes

2024-06-26 19:47 UTC, QuLogic requested changes
This apparently breaks `SpanSelector`.

2024-06-26 19:51 UTC, tacaswell commented
This is also going to break `_changed_canvas` which we use to suppress events durring saving (see https://github.com/matplotlib/matplotlib/pull/25085 / 6bb208d5a9c46ded307c7baef4fd255cdbc80c46 )

2024-06-27 13:49 UTC, tacaswell commented on lib/matplotlib/widgets.py
> +        if _init or self.canvas is not ax.figure.canvas:
```suggestion
        if _init:
```

The second part will never be true now.

2024-06-27 14:19 UTC, anntzer commented
Now fixed; the test failure is unrelated.

2024-06-27 16:23 UTC, ksunden commented
Test failure is not unrelated, it is the newly added test

2024-07-03 19:44 UTC, tacaswell commented on lib/matplotlib/widgets.py
> +        if _init or self.canvas is not ax.figure.canvas:
It was pointed out I am wrong about being wrong.

2024-07-03 19:54 UTC, QuLogic approved these changes

2024-07-03 21:10 UTC, ksunden approved these changes
Anyone can merge on CI finishing

2024-07-04 00:15 UTC, merged