Set default
matplotlib/matplotlib pull request #28528
Opened 2024-07-09 07:04 UTC by bollenn

## PR summary
With a "fresh" install I was getting

```
    import matplotlib.pyplot as plt  # noqa: E402 pylint: disable=wrong-import-position
/home/developer/.local/lib/python3.9/site-packages/matplotlib/pyplot.py:55: in <module>
    import matplotlib.colorbar
/home/developer/.local/lib/python3.9/site-packages/matplotlib/colorbar.py:19: in <module>
    from matplotlib import _api, cbook, collections, cm, colors, contour, ticker
/home/developer/.local/lib/python3.9/site-packages/matplotlib/contour.py:15: in <module>
    from matplotlib.backend_bases import MouseButton
/home/developer/.local/lib/python3.9/site-packages/matplotlib/backend_bases.py:49: in <module>
    from matplotlib import (
/home/developer/.local/lib/python3.9/site-packages/matplotlib/text.py:16: in <module>
    from .font_manager import FontProperties
/home/developer/.local/lib/python3.9/site-packages/matplotlib/font_manager.py:1588: in <module>
    fontManager = _load_fontmanager()
/home/developer/.local/lib/python3.9/site-packages/matplotlib/font_manager.py:1583: in _load_fontmanager
    json_dump(fm, fm_path)
/home/developer/.local/lib/python3.9/site-packages/matplotlib/font_manager.py:970: in json_dump
    json.dump(data, fh, cls=_JSONEncoder, indent=2)
/home/developer/.local/lib/python3.9/site-packages/json_numpy.py:54: in dump
    return _dump(*args, **kwargs)
/usr/local/lib/python3.9/json/__init__.py:179: in dump
    for chunk in iterable:
/usr/local/lib/python3.9/json/encoder.py:438: in _iterencode
    o = _default(o)
/home/developer/.local/lib/python3.9/site-packages/json_numpy.py:24: in default
    raise TypeError(msg)
E   TypeError: Object of type <class 'matplotlib.font_manager.FontManager'> is not JSON serializable
```

Herewith that is fixed

## PR checklist

- [ ] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [ ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [ ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

2024-07-09 15:21 UTC, tacaswell commented
Thank you for your work on this, but I'm against merging this.  

https://github.com/Crimson-Crow/json-numpy/blob/7181b2a679c63f566706986a339a99bb95ea96b0/json_numpy.py#L62-L67 is what I think is `json_numpy.patch()`.  It is not clear to me why this is breaking us, but my quick read is that we are extending json they way it is intended and `json_numpy` is (enabling) doing something a bit questionable. 

I think this should be reported as a bug to json_numpy.

2024-07-09 15:21 UTC, tacaswell requested changes
I think this is a bug in `json_numpy` which we should not be working around.

2024-07-09 19:14 UTC, bollenn commented
@tacaswell I agree with the statement that it is a `json_numpy` issue, and as such this PR probably does not need merging.

On the other hand I could not yet come up with a valid improvement for `json_numpy` to overcome this issue :rofl:

2024-07-16 04:43 UTC, bollenn commented
Issue was fixed in `json_numpy` via https://github.com/Crimson-Crow/json-numpy/pull/3

2024-07-16 04:43 UTC, closed without merging