MNT: Error out if plt.polar() is called with an existing non-polar Axes
matplotlib/matplotlib pull request #28946
Opened 2024-10-07 11:38 UTC by timhoffm

Before, we only issued a warning. But we clearly cannot fulfill the intention of a polar plot and therefore we should error out instead of just warn.

Also document that `polar()` should typically be called first to prevent having a non-polar Axes already created.

Closes #28944.

2024-10-07 12:07 UTC, rcomer approved these changes

2024-10-07 12:07 UTC, rcomer commented on lib/matplotlib/pyplot.py
> +        before can lead to the implicit creation of a rectangular Axes, in which
```suggestion
        before this can lead to the implicit creation of a rectangular Axes, in which
```
Tiny nit - this scans better for me.

2024-10-07 19:54 UTC, tacaswell requested changes
👍🏻 , but I would like to hold this until after we branch 3.10.x and it needs an API change note.

Although I am coming down in favor of doing this, I'm a bit torn.  Clearly what it is doing now is not what anyone wants, but it is not "wrong".  Introducing a new hard-fail is a breaking change to what I believe is long standing behavior so needs an API change note and I would like to defer it to 3.11 to have a bit more time (and early adopters) to try it.

2024-10-07 21:11 UTC, timhoffm commented
IMHO the current behavior is actually "wrong". Not wrong in the sense that pyplot works exactly to its rules, but logically wrong: If I write `plt.polar(...)` I clearly expect the data to show up in a polar Axes. It's surprising and nobody helped with that the data may end up in a rectilinear Axes. Since we cannot fulfill the polar Axes according to pyplot Axes-reuse rule if another Axes has already been created, the only reasonable action is to deny the operation and error out.

While this is technically a breaking change, I'm not worried about it. Every affected use case I can imagine, is a hidden error that does not do what the user wants, and it's justifiable to surface that immediately through an exception.
But if you are seriously concerned about the breaking change, we could also officially deprecate the behavior (then maybe already for 3.10? but OTOH it's not urgent) and turn it into an error later.

2024-10-28 12:44 UTC, timhoffm commented
I've heard [the concerns](https://github.com/matplotlib/matplotlib/pull/28946#pullrequestreview-2352817076) and turned it into a regular deprecation rather than an immediate failure.

But then, I'd like to punt back to 3.10 to get the deprecation rolling.

2024-10-29 21:10 UTC, greglucas approved these changes

2024-10-29 21:10 UTC, merged

2024-10-29 21:11 UTC, greglucas commented
:+1: to the deprecation note. If someone complains, they can then fix it and we can change this note.