Add hatchcolor parameter for Collections
matplotlib/matplotlib pull request #29044
Opened 2024-10-30 18:44 UTC by Impaler343

## PR summary

Follow on PR to #28104 helping to fix issues #26074 and #7059
Added `hatchcolor` parameter for Collections, to be able to separately control _edgecolors_ and _hatchcolors_.  

The fallback logic for `hatchcolor` is identical to the previous PR, where it follows this precedence order:

`hatchcolor` parameter -> `hatch.color` rcParam -> inherit from `edgecolors` if specified -> default to `patch.edgecolor` rcParam if `edgecolors` is not specified.

1. If `hatchcolor` parameter is specified, it will take precedence over `hatch.color` rcParam and `edgecolors`.
2. If `hatchcolor` is not specified, it will try to use `hatch.color` rcParam. If this rcParam is a valid color, it will be used for the hatches.
3. If `hatch.color` rcParam is **inherit**, the hatches will inherit the color from `edgecolors` if it is specified.
4. If `edgecolors` is not specified, the hatches will default to `patch.edgecolor`.

- [ ] Need to rewrite the failing test(s)

## PR checklist

- [x] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [ ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [ ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

2024-10-31 02:37 UTC, Impaler343 commented
Yes, preferably, so that the changes for Patches can be accurately replicated for Collections

2024-10-31 03:43 UTC, r3kste commented
There is currently one test which is failing and might need a rewrite: `lib/matplotlib/tests/test_axes.py::test_contour_hatching`

### Previous Behavior

In collections, hatchcolor is set along with edgecolor.

In the cases where `edgecolors` is explicitly specified by the user, `hatchcolor` is set to the first color in edgecolors and it also uses the alpha value specified by the user. However, if `edgecolors` is not specified, `hatchcolor` uses `mpl.rcParams['hatch.color']` for the color, but it doesn't use the alpha value specified by the user.

### New Behavior

The new implementation in this PR has hatchcolor separated from edgecolor and it uses the alpha value specified by the user, regardless of whether edgecolors is specified or not.

#### Reason for New Behavior

`alpha` works on `hatchcolor` when `edgecolors` is specified. Therefore, I believe that it should also work when `edgecolors` is not specified.

In the above test, `alpha` is set to 0.5. Ideally, the hatch should have an alpha value of 0.5, but it has the default alpha value of 1.0.

2025-01-03 12:19 UTC, Impaler343 commented
pinging @story645 for review

2025-01-03 12:37 UTC, r3kste commented
The PDF test for `test_axes.py::test_contour_hatching` isn't failing, so the baseline PDF is left untouched. I suspect that this is because alpha on hatches on PDF backend isn't completely implemented and it looks like #17049 aims to fix this.

2025-01-25 15:38 UTC, timhoffm reviewed
It's somewhat unfortunate that we have to put the parameter at the end of each function signature and make it optional on all lower-level functions. But I suppose that is the price we have to pay to keep API backward compatibility. I would have to check how public all this is and whether we could eventually migrate to a cleaner API.

2025-01-25 15:38 UTC, timhoffm commented on lib/matplotlib/tests/baseline_images/test_axes/contour_hatching.png
Why do these images have to be changed? AFAICS you haven't modified the test. This would mean, whe have a change of default behavior. Can that be avoided?
If there are fundamental reasons that the default changes. We need to (1) document this in the what's new note. (2) I suggest to modifying the test instead (likely by  setting an explicit hatch color) so that the tests images do not need update. Generally, we try to use as few images as possible and changes them as a rarely as possible, because the images bloat the git repo.

2025-01-25 15:40 UTC, timhoffm commented on doc/users/next_whats_new/separated_hatchcolor.rst
> +    ax.scatter(
The scatter example is a bit artificial. Would it be more instructive to e.g. use a stackplot as an example?

2025-01-26 07:41 UTC, r3kste commented
> AFAICS you haven't modified the test. This would mean, whe have a change of default behavior. Can that be avoided?

I think that we can't avoid this change, because the default behavior is somewhat inconsistent, as explained in this [comment](https://github.com/matplotlib/matplotlib/pull/29044#issuecomment-2448956092).

> (2) I suggest to modifying the test instead (likely by setting an explicit hatch color) so that the tests images do not need update. Generally, we try to use as few images as possible and changes them as a rarely as possible, because the images bloat the git repo.

I think it might be better to update the images, because it looks like the test was previously testing the incorrect behavior. I think that it is better to have the test images reflect the correct behavior, as this test covers the behavior of hatchcolors with alpha values more comprehensively than if we change the test to explicitly set the hatch color to black with alpha = 1.0.

When explicitly setting hatchcolor, I wasn't able to force alpha as 1.0 for hatchcolor without using `_hatchcolors` attribute.

```diff
diff --git a/lib/matplotlib/tests/test_axes.py b/lib/matplotlib/tests/test_axes.py
index 38857e846c..5764d3fff6 100644
--- a/lib/matplotlib/tests/test_axes.py
+++ b/lib/matplotlib/tests/test_axes.py
@@ -2651,6 +2651,9 @@ def test_contour_hatching():
                 cmap=mpl.colormaps['gray'],
                 extend='both', alpha=0.5)
    
+    for c in ax.collections:
+        c._hatchcolors = mpl.colors.to_rgba_array('black', 1.0)
+
 
 @image_comparison(
     ['contour_colorbar'], style='mpl20',
```

Here is why I think that the test was previously testing the incorrect behavior:
For a stackplot, with alpha = 0.3

| | Previous Behavior | New Behavior (PR) |
|----------|----------|----------|
| `edgecolor = 'black'` | ![prev_black](https://github.com/user-attachments/assets/fabaef53-3590-4236-ab02-deeb050c75a5) | ![new_black](https://github.com/user-attachments/assets/5167b642-5a5a-410d-b7f4-a92333781900) |
| `edgecolor = None` | ![prev_none](https://github.com/user-attachments/assets/605df1c9-ee94-454a-b11c-d6c11a05ef02) | ![new_none](https://github.com/user-attachments/assets/9fbcc23e-623b-48b5-8d81-8c6cca2e7d07) |

2025-01-26 10:42 UTC, timhoffm commented
Thanks for the clarification. I agree it's consistent to apply a global alpha to hatchcolor as well.

> When explicitly setting hatchcolor, I wasn't able to force alpha as 1.0 for hatchcolor without using `_hatchcolors` attribute.

That's unfortunate, because it effectively means, one cannot apply alpha to the fill while keeping the hatch fully opaque. 😢  Essentially, the problem is that we cannot explicitly control the alpha for a fill that is created via a colormap. It may be reasonable to create a `cmap.with_alpha()` method to be able to make semi-transparent colormaps. The test could then be written as
```
    ax.contourf(x, y, z, 7, hatches=['/', '\\', '//', '-'],
                cmap=mpl.colormaps['gray'].with_alpha(0.5),
                extend='both')
```

2025-01-26 19:31 UTC, r3kste commented on doc/users/next_whats_new/separated_hatchcolor.rst
> +    ax.scatter(
I agree that a stackplot would be a better example to include. However, due to the way how stackplot is implemented, passing the `hatchcolor` parameter doesn't provide the 'desired/expected' output. Each 'stack' is a separate collection, and each of them are set the same hatchcolors, instead of them being cycled and applied individually.

Ideally in order to fix this, something similar to #27158 needs to be done for `hatchcolor`

2025-02-01 14:52 UTC, timhoffm commented
Doc build failure is indirectly related, because we have a fragile method of excluding some doc warnings. This will be remedied by #29560. We should wait and rebase to fix this.

2025-02-05 02:47 UTC, timhoffm commented on lib/matplotlib/backend_bases.py
> +            hatchcolors = []
I‘m not sure about the pattern. We do prefer
```
b = x if a is None else y
```
Over
```
If a is None:
    b = x
else:
    b = y
```
But just coercing a variable through an if is fine to me, and even slightly preferable.

2025-02-05 02:51 UTC, timhoffm commented on lib/matplotlib/backend_bases.py
> +                         antialiaseds, urls, offset_position, hatchcolors=None):
To be checked: Do 3rd party backend implementations depend on this?

2025-02-05 08:55 UTC, timhoffm commented on lib/matplotlib/backend_bases.py
> +            hatchcolors = []
The if-else branch case where both branches assign to the same variable is indeedd better written using the ternary if else expression, because it communicates that we assign a new variable `b`. 

The case here is different because we conditionally modify the variable, in particular it's a simple default setting, which IMHO is more clear in the if statement.

Checking the code, I've only found three cases that use the ternary operator for default setting,
- two in `test_image.py` (subset of regex `= \w+ if \w+ is None else`)
- one in `hinton_demo.py` (subset of regex `= \w+ if \w+ is not None else`)

2025-02-05 08:56 UTC, timhoffm commented
@Impaler343 #29561 fixes the doc build issue. Please rebase to pick that up.

2025-02-05 10:01 UTC, Impaler343 commented on lib/matplotlib/tests/test_collections.py
> +    colors_2 = ['orange', 'cyan', 'blue', 'magenta']
As these lists are not purely used for setting edgecolor or hatchcolor, we really cant label them as so

2025-02-05 10:09 UTC, Impaler343 commented on lib/matplotlib/collections.py
> +            if len(self.get_edgecolor()) == 0:
Yes, we are checking if the array is empty or not. Is there a better way to do so? Like
```python
if not self.get_edgecolor().size:
```

2025-02-05 10:22 UTC, r3kste commented on lib/matplotlib/backend_bases.py
> +                         antialiaseds, urls, offset_position, hatchcolors=None):
I want to add that this is also used in `test_backend_bases.py::test_uses_per_path`, which directly calls `_iter_collection`. So, I believe it is better to keep it optional.

https://github.com/matplotlib/matplotlib/blob/f42d451b02d59912d955fb8972cb75dc18b76272/lib/matplotlib/tests/test_backend_bases.py#L36-L40

2025-02-08 14:28 UTC, r3kste commented
Added `test_draw_path_collection_no_hatchcolor` for covering the `hatchcolors is None` cases. 

However, I believe the _Minimum Versions_ test is failing because of `numpy==1.23.0` raising a **DeprecationWarning**  at Line-2605, instead of a **ValueError** like future versions of numpy.

https://github.com/matplotlib/matplotlib/blob/91f52bc8b8e8840cfbdd990409308d6bcb541648/lib/matplotlib/backends/backend_pdf.py#L2601-L2610

One way to fix this might be to catch DeprecationWarning also in the except block. I would like to hear other thoughts on this.

```diff
diff --git a/lib/matplotlib/backends/backend_pdf.py b/lib/matplotlib/backends/backend_pdf.py
index 0607b54554..3fc920c5e0 100644
--- a/lib/matplotlib/backends/backend_pdf.py
+++ b/lib/matplotlib/backends/backend_pdf.py
@@ -2606,7 +2606,7 @@ class GraphicsContextPdf(GraphicsContextBase):
                         different = ours is not theirs
                     else:
                         different = bool(ours != theirs)
-                except ValueError:
+                except (ValueError, DeprecationWarning):
                     ours = np.asarray(ours)
                     theirs = np.asarray(theirs)
                     different = (ours.shape != theirs.shape or
```

2025-02-11 10:04 UTC, timhoffm commented
@r3kste Why is this error surfacing in this PR? What are we doing different with hatchcolor than with other colors? - Or more precisely what are `ours` and `theirs` in the context of failure.

2025-02-11 10:51 UTC, r3kste commented
> Or more precisely what are `ours` and `theirs` in the context of failure.

It seems to be `_fillcolor` that is causing this.

param: _fillcolor
ours: (0.0, 0.0, 0.0)
theirs: array([0., 0., 1., 1.])

2025-02-11 13:57 UTC, anntzer requested changes
@timhoffm Thanks for the heads up re: 3rd-party backends.  Yes, this will definitely break them (e.g. mplcairo), I'll try to write up something about how to address this in the coming days.

2025-02-13 10:19 UTC, anntzer commented
The problem is that this PR modifies the call signatures of `draw_path_collection` (and similarly `draw_quad_mesh` -- everything applies more or less the same, but see below as well), meaning that third-party rendering backends (e.g. mplcairo) will completely break until either 1) they are updated to support the new `hatchcolors` argument, or 2) matplotlib detects that the third-party backend only supports the old signature, and falls back, when necessary to the slow `RendererBase.draw_path_collection` in that case (which will draw the collection via repeated calls to the renderer's `draw_path`.

I will assume that 1) is not acceptable (well, I would find it annoying as mplcairo maintainer, at least).  The difficulty with 2) is that until now, matplotlib has not required the signature of third-party `draw_path_collection` implementations to be introspectable e.g. with `inspect.signature`, and indeed, mplcairo's `draw_path_collection` doesn't support `inspect.signature` (due to a limitation in pybind11) or even kwargs (because I never bothered).  I can see two "safe" and not-too-horrible approaches, neither of which is really nice:

1) Add an explicit flag on the renderer_class, `supports_collection_hatchcolors`, ask third-parties to set this to True if they support it, check that flag, and dispatch based on that (a bit ugly, and then raises the question of whether we want to remove that flag in the long term), or

2) Still try to introspect whether the renderer supports `hatchcolors` by first making an "empty call" `renderer.draw_path_collection(...)` with zero paths but still passing hatchcolors and check whether that raises a TypeError or not, assuming that TypeError means that `hatchcolors` is not supported (one could try to cache that information per implementation of `draw_path_collection` though I'm not sure that's really worth it as the empty call should be cheap compared to the real call).

If we're going to go through either dance, then probably it would be a good time to also change `draw_path_collection` to *also* support multiple kinds of hatches (i.e. add a `hatches=...` arg (likely just before hatchcolors)); there's real need for that in `ContourSet.draw` (which currently just falls back to drawing contours one at a time when hatch-filled contours are requested).

Regarding `draw_quad_mesh`, an additional point I would like to raise an additional point, which is that I'm not sure whether the low-level `draw_quad_mesh` should really support hatchcolors (or even hatching at all).  I think meshes tend to have a specific meaning in rendering libraries (see [cairo_pattern_create_mesh](https://www.cairographics.org/manual/cairo-cairo-pattern-t.html#cairo-pattern-create-mesh) or tiling patterns in the pdf standard) and at least on mplcairo's side, asking for hatching support would effectively lead to mplcairo adding a fallback to a `draw_path_collection`-like approach of drawing each quad separately.  I would suggest that if the high-level `QuadMesh` class really needs to support hatching then that fallback should just happen in `QuadMesh.draw`, rather than requiring third-parties to do it.

2025-02-13 11:15 UTC, timhoffm commented
A more formalized version of (i) would be to introduce backend API versions. We'd declare the current state as version 1. Backends then would need to declare which versions they are written for (and if they don't we assume version 1). The effort here would be a bit larger as we'd need to formalize what exactly is part of the backend API, but it makes detection simpler and also would open a path for the evolution of the API; e.g. we declare the new hatch stuff as v2. Matplotlib will for a given period accepts backends with v1 and v2 and will maintain internal logic to do the appropirate calls. We can then deprecate support on v1 backends (also with a nice runtime warning) and eventually drop support cleanly to simplify our logic again.

2025-02-13 15:38 UTC, anntzer commented
Sure, explicit API versions would work too (if we're going that route, I would also get rid of the now unused `offset_position` arg).  Actually there's yet another approach (if we're willing to have a one-time API break), likely more elegant, which is to move to an API closer to draw_path, where most arguments (color, etc.) are not actually passed to draw_path but rather set via GraphicsContext.set_color (etc.) and then the GraphicsContext object (effectively something like a dataclass) is passed to draw_path.  The advantage here re: compat is that it becomes possible to say e.g. "third-party GraphicsContext *must* inherit from GraphicsContextBase", so GraphicsContext.set_hatchcolors will always be present; third-party backends still need to update themselves to actually read that info but won't be completely broken in the meantime.  I would also consider this more elegant than continuously adding more and more arguments to the very long argument list of draw_path_collection...

2025-02-13 16:23 UTC, timhoffm commented
Using a GraphicsContext sounds reasonable. But that's a change I would also combine with introducing more formal API versioning.

2025-02-13 23:03 UTC, timhoffm commented
No, #28104 is not affected, because it's not changing the backend API.

2025-02-14 15:16 UTC, anntzer commented
I think that if we want to move this PR forward, the realistic short-term approach is to do API support sniffing via the empty call (and not even warn on third-parties for now, at least until we can agree on the long-term plan and likely also add support for multiple hatches).

2025-02-17 10:39 UTC, anntzer commented
Thanks @Impaler343 for adding the API sniffing.  Unfortunately this is not enough, because you choose to just not pass hatchcolors at all if they are unsupported.  While the idea of just drawing single-color hatches on 3rd-party backends may be reasonable (I'm fine with that), it means that these backends will try to consult rcParams["hatch.color"] to select a color; and since #28104 they can see the new unnormalized value "edge", for which there was no support before, and they will crash there.  At least this value should be normalized (e.g. to the first edgecolor, I guess); ideally if hatchcolors is not supported, the draw_path_collection call should be expanded as in ContourSet.draw to draw one path at a time.

2025-02-22 16:49 UTC, anntzer commented
This works now on mplcairo.  Thanks for going through all the work!
I haven't carefully reviewed the implementation yet but the general approach looks fine to me.  Perhaps add a note that the current new API is provisional, as I expect that it will change in the future at least to support multiple hatches as well?  (I would rather only change things on mplcairo's side once multiple hatches are supported too.)

2025-03-15 03:48 UTC, r3kste commented
@anntzer Are there any other changes expected? Or is this ready to be merged?

2025-03-16 11:21 UTC, anntzer commented on lib/matplotlib/backend_bases.py
> +                             offset_position, hatchcolors=None):
Make this keyword-only (everywhere throughout the PR) so that if later we decide to add e.g. a `hatches` kwarg it can go before hatchcolors?

2025-03-16 11:23 UTC, anntzer approved these changes
Just one last suggestion to improve on the future extensibility (approval is conditional on at least discussing it).
I still don't really like the API but it's also unrealistic to hope for a full rewrite here, so let's go with it.

2025-03-21 07:35 UTC, r3kste commented
> I still don't really like the API but it's also unrealistic to hope for a full rewrite here, so let's go with it.

I agree that this API will need to be changed in the future. 

@timhoffm any suggestions?

2025-03-21 19:01 UTC, dstansby reviewed
Thanks for this PR - it looks great overall, and the examples were super nice to understand the new feature.

There's a few minor points I think can be improved, and some questions I had - I've left my comments inline in the code.

2025-03-21 19:01 UTC, dstansby commented on lib/matplotlib/tests/test_axes.py
> +                extend='both')
This seems unrelated to the other changes in this PR - is it neccessary to get the tests to pass? Does this mean the behaviour of passing `alpha=0.5` to `countourf` has now changed?

2025-03-22 09:30 UTC, r3kste commented on doc/users/next_whats_new/separated_hatchcolor.rst
> +    y = np.random.rand(20)
This was changed to be random, due to this [comment](https://github.com/matplotlib/matplotlib/pull/29044#discussion_r1929870530):

> I suggest to place the scatter elements randomly instead of on an y=x^2 line. This functional relationship is quite atypical for scatter and may be rather distracting as a visual structure compared to randomly distributed markers with different hatches.

2025-03-22 09:31 UTC, r3kste commented on galleries/examples/shapes_and_collections/hatchcolor_demo.py
> +    marker="h",  # Use hexagon as marker
Unfortunately, I couldn't find a more descriptive value in `matplotlib.markers`.

2025-03-22 09:32 UTC, r3kste commented on lib/matplotlib/backend_bases.pyi
> +        hatchcolors: ColorType | Sequence[ColorType] | None = None,
Yes, it is intended. The value 'edge' should be resolved to the edgecolor before it reaches the backend.

2025-03-22 09:33 UTC, r3kste commented on lib/matplotlib/collections.py
> +            except TypeError:
As explained by anntzer in this [comment](https://github.com/matplotlib/matplotlib/pull/29044#issuecomment-2656133496),

> matplotlib has not required the signature of third-party draw_path_collection implementations to be introspectable e.g. with inspect.signature

2025-03-22 09:34 UTC, r3kste commented on lib/matplotlib/collections.py
> +                hatchcolors_arg_supported = False
These lines are run only in the case of a third-party backend. However, I am not sure how to test this within the current testing framework of matplotlib, without a third-party backend.

2025-03-22 09:36 UTC, r3kste commented on lib/matplotlib/tests/test_axes.py
> +                extend='both')
Yes. It is necessary as discussed in [comment1](https://github.com/matplotlib/matplotlib/pull/29044#issuecomment-2614257379) and [comment2](https://github.com/matplotlib/matplotlib/pull/29044#issuecomment-2614320129). This is because the previous behavior was inconsistent.

2025-03-24 16:28 UTC, timhoffm commented on lib/matplotlib/backend_bases.py
> +                       antialiased, edgecolors, hatchcolors=None):
Is this a red herring? From what I understand from https://github.com/matplotlib/matplotlib/pull/29044#issuecomment-2656133496, making hatchcolors optional (or even kw-only) does not buy us anything in terms of better API compatibility: This is reimplemented by backends. Some may have implemented a `hatchcolors` parameter, others may not. It is only called from our matplotlib code, so we anyway have to deal with it being available or not (and if it's available, we always want to pass hatchcolors). There shouldn't be any third-party/user code needing to call this function.

If that's correct, an additional positional parameter would have the same effect. And then I'd prefer that because it keeps the whole function consistent.

ping @anntzer Am I correct here?

---

Edit: There seem to be very few "real" usages of `draw_path_collection` (I've tried to filter outforks or copies of our files):
https://github.com/search?q=%2F%5C.draw_path_collection%5C%28%2F+language%3APython+NOT+is%3Afork+NOT+repo%3Amatplotlib%2Fmatplotlib+NOT+path%3A**%2Fbackend_bases.py+NOT+path%3A**%2Fcollections.py++NOT+path%3A**%2Fpatheffects.py+NOT+path%3A**%2Fbackend_agg.py+NOT+path%3A**%2Fbackend_svg.py+NOT+path%3A**%2Fbackend_pdf.py++NOT+path%3A**%2Fbackend_ps.py+NOT+path%3A**%2Fbackend_macosx.py++NOT+path%3A**%2Fleft.py+NOT+path%3A**%2Fright.py++NOT+path%3A**%2Fmerge.py++NOT+path%3A**%2Fbase.py+NOT+path%3A**%2Fsite-packages%2F**&type=code

I think making this optional is meaningful for a start because it will support some very rare use cases. But in terms of API consistency, I'd like to move this to a regular parameter in the future, i.e.
- not make this kw-only right now
- some time later deprecate calling this function without `hatchcolors`

@anntzer @dstansby @r3kste Does that make sense?

2025-03-24 17:37 UTC, anntzer commented
re: making hatchcolors optional and API compatibility:
My point of view is that the renderer API (draw_foo) is public and it is legitimate for 3rd-parties to call it directly (e.g. they can create their own artist subclasses that implement their own draw() and call draw_foo() from there.  However, I guess it could also be reasonable(?), and possibly helpful for extensibility, to declare that these methods are *not* for 3rd-party direct use, and that third-party artists *must* go through a builtin artist's draw to invoke the renderer's drawing functions.  But that's definitely not a policy we have stated so far.

2025-03-24 18:06 UTC, dstansby commented on doc/users/next_whats_new/separated_hatchcolor.rst
> +    y = np.random.rand(20)
👍 in that case happy to leave this as is

2025-03-24 18:26 UTC, timhoffm commented
Thanks. I agree *optional* is set to begin with for compatibility.

Questions are:

- Do we want/gain anything with keyword-only? - I tend towards no.
- Do we want to evolve the API to non-optional through regular deprecation machinery? - I tend towards yes.

2025-03-24 19:32 UTC, anntzer commented
> * Do we want/gain anything with keyword-only? - I tend towards no.

It makes it easier to later include parameters *before* it, e.g. `hatches` is something that's clearly missing and would be expected to come first.

> * Do we want to evolve the API to non-optional through regular deprecation machinery? - I tend towards yes.

Let's not for now.  As argued above I think the API introduced in this PR is actually not so great (but still the best that can be done without an in-depth reworking of draw_path_collection), so e.g. I'd rather not implement support for it at all in mplcairo (and instead rely on Matplotlib's fallback implementation) until a better API comes.  Likewise I don't think we should encourage any third parties to implement it.

2025-03-28 23:43 UTC, timhoffm commented on lib/matplotlib/collections.py
> +                        renderer.draw_path(gc0, path, transform, rgbFace)
For better backward-compatibility/performance, would it be reasonable to split the "backend does not support hatchcolors" into
```
if no_hatches_needed:
    renderer_draw_path_collection(...) # no hatch colors passed
else:
    # unroll the collection to draw paths in a loop
```
I'm unclear how performance-critical this is and whether we can unversally force the collection unrolling on backends that do not support hatchcolors.

ping @anntzer

2025-03-29 15:58 UTC, anntzer commented on lib/matplotlib/collections.py
> +                        renderer.draw_path(gc0, path, transform, rgbFace)
Good catch.  I agree that only going through the unrolled version when hatchcolors are actually passed would be much better.

2025-03-31 09:59 UTC, timhoffm approved these changes

2025-03-31 09:59 UTC, merged

2025-03-31 10:01 UTC, timhoffm commented
Thanks @r3kste for going through all the nitty gritty details with us!